Änderungen am Board für phpBB 3.1.10-RC1
phpbb-de/phpbb-translation pull request #308
Opened 2016-09-26 17:58 UTC by Philipp-K

2016-09-26 17:59 UTC, Philipp-K commented on language/de/migrator.php
> +	'MODULE_EXIST_MULTIPLE'				=> 'Es existieren mehrere Module mit dem angegebenen übergeordneten Sprachnamen: %s. Verwende die Nach-Oben-/Nach-Unten-Schaltflächen, um die Position des Moduls festzuleg
Kann das mal jemand prüfen? Ich hab das mehr nach Bauchgefühl übersetzt :-)

2016-09-26 17:59 UTC, Philipp-K commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Auch hier wäre eine Prüfung nett

2016-09-27 20:55 UTC, Crizz0 requested changes

2016-09-27 20:55 UTC, Crizz0 commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
verlinken wir nicht sonst immer auf das Download-Paket? 

> wo sich die Datei

Vlt. "in der sich die Datei... befindet"?

2016-09-27 20:55 UTC, Crizz0 commented on language/de/install.php
> +	'UPDATE_INCOMPLETE'				=> 'Deine phpBB-Version wurde nicht erfolgreich aktualisiert.',
"phpBB-Installation" passt hier imho besser.

2016-09-27 20:55 UTC, Crizz0 commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Evtl. passt "Name" besser, anstelle von Kennung.

2016-09-27 20:55 UTC, Crizz0 commented on language/de/migrator.php
> +	'MODULE_EXIST_MULTIPLE'				=> 'Es existieren mehrere Module mit dem angegebenen übergeordneten Sprachnamen: %s. Verwende die Nach-Oben-/Nach-Unten-Schaltflächen, um die Position des Moduls festzuleg
"langname" ist aber wirklich ein seltsames Konstrukt. 

Einfach nur "Name" ist vielleicht simpler und verständlicher?

2016-09-30 20:32 UTC, gn36 commented on language/de/migrator.php
> +	'MODULE_EXIST_MULTIPLE'				=> 'Es existieren mehrere Module mit dem angegebenen übergeordneten Sprachnamen: %s. Verwende die Nach-Oben-/Nach-Unten-Schaltflächen, um die Position des Moduls festzuleg
In welchem Bezug wird das benutzt? für "DE" wenn "de" und "de-x-sie" zur Verfügung stehen (oder "en" und "en-us" z.B.)?

2016-09-30 20:42 UTC, gn36 commented on language/de/migrator.php
> +	'MODULE_EXIST_MULTIPLE'				=> 'Es existieren mehrere Module mit dem angegebenen übergeordneten Sprachnamen: %s. Verwende die Nach-Oben-/Nach-Unten-Schaltflächen, um die Position des Moduls festzuleg
Ok, hier ist denke ich wirklich der dem Benutzer angezeigte Modulname des Elternmoduls gemeint. Also bei einem neuen Modul, das im UCP bei den Privaten Nachrichten einsortiert werden soll z.B. vermutlich sowas wie "UCP_PM". Das ist bei mitgelieferten Modulen immer eine Sprachvariable, bei offiziell freigegebenen Erweiterungen auch, muss aber strenggenommen nicht so sein, man kann auch einen eigenen Namen eingeben (was dann die Installation von Erweiterungen ziemlich über den Haufen wirft wenn es Module gibt). Insofern finde ich das sogar Englisch falsch.

Für uns finde ich einfach "Name" aber auch besser. Mit diesen Details muss man den Nutzer ja nicht behelligen.

2016-09-30 20:44 UTC, gn36 commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Genau, das gehört denke ich zusammen und sollte einheitlich bezeichnet werden. Oben findet es das Elternmodul mehrmals, hier gar nicht.

2016-10-03 20:28 UTC, Philipp-K commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
Wie meinst du das mit dem Download-Paket?

> Vlt. "in der sich die Datei... befindet"? 
Wenn, dann "in dem sich...", oder?

2016-10-03 20:29 UTC, Philipp-K commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Dann aber "Ein übergeordnetes Modul mit dem passenden Namen", oder?

2016-10-03 20:32 UTC, Crizz0 commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
Naja, sonst verlinken wir das Wort direkt auf das passende Paket bzw. zusätzlich aufs De-Paket. Hier nicht. 

Und ja, deine 2. Variante ist auch gut

2016-10-03 21:13 UTC, gn36 commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Hm. Vielleicht besser:
> Es wurde kein übergeordnetes Modul mit diesem Namen gefunden: %s

und oben dann analog:
> Es wurden mehrere übergeordnete Module mit dem angegebenen Namen gefunden: %s. Verwende die Nach-Oben-/Nach-Unten-Schaltflächen, um die Position des Moduls festzulegen.

2016-10-03 21:21 UTC, gn36 commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
"Wo" finde ich auch holprig. "in dem" oder auch "in welchem" finde ich auch besser.

2016-10-04 19:50 UTC, Philipp-K commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Hab ich jetzt mal so übernommen. Wobei ich mir nicht sicher bin, ob sich %s auf das Modul bezieht, das nicht gefunden wurde oder auf das, dessen übergeordnetes Modul nicht gefunden wurde.

2016-10-04 19:56 UTC, Philipp-K commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
Wo gestrichen und Link auf das deutsche Paket aufgenommen. Das mit dem Wort verlinken kann ich gerade nicht greifen.

2016-10-04 19:58 UTC, Crizz0 commented on language/de/install.php
> +		<p>Das letzte Update deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe das <a href="%1$s" title="%1$s">database_update-Skript</a> auf und führe es durch. Falls es fehlt, lade bit
So passt es doch. 👍

2016-10-04 20:00 UTC, gn36 commented on language/de/migrator.php
> +	'PARENT_MODULE_FIND_ERROR'			=> 'Die Kennung des übergeordneten Moduls konnte nicht gefunden werden: %s',
Bezieht sich auf das übergeordnete Modul würde ich sagen:
> throw new \phpbb\db\migration\exception('PARENT_MODULE_FIND_ERROR', $data['parent_id']);

Das ist die einzige Stelle, wo die Sprachvariable eingesetzt wird (phpBB/phpbb/db/migration/tool/module.php). 

Genauso oben:
> throw new \phpbb\db\migration\exception('MODULE_EXIST_MULTIPLE', $parent_id);

Imho sollte das also so passen.

2016-10-04 20:07 UTC, Crizz0 approved these changes

2016-10-05 19:37 UTC, Crizz0 commented
@gn36 Von deiner Seite auch alles i.O. hier?

2016-10-07 05:26 UTC, merged

2016-10-07 05:47 UTC, gn36 commented
Hier gibt's ziemlich große Konflikte beim Merge nach 3.2.x das kann ich jetzt auf die Schnelle nicht machen sondern muss ich mir in Ruhe anschauen.

2016-10-07 06:05 UTC, Crizz0 commented
Ich kann es mir heute Abend auch anschauen.

2016-10-07 12:15 UTC, gn36 commented
Wäre super, ich komm da heute Abend nicht zu.

Am 7. Oktober 2016 08:05:37 MESZ, schrieb Christian Schnegelberger <notifications@github.com>:
>Ich kann es mir heute Abend auch anschauen. 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb-de/phpbb-translation/pull/308#issuecomment-252160467

2016-10-07 15:34 UTC, Crizz0 commented
Habe ich gemacht, das war primär die install.php, da dort von 3.1.x zu 3.2.x die Struktur völlig anders ist.