Translation for 3.2.0-RC2 part1: with language/en/acp/*.php
phpbb-de/phpbb-translation pull request #311
Opened 2016-12-11 13:19 UTC by Crizz0

Änderungen an:
/phpBB/language/en/acp/*.php

#310 Part 1

2016-12-11 17:25 UTC, gn36 requested changes
Ansonsten ok.

2016-12-11 17:25 UTC, gn36 commented on language/de_x_sie/acp/common.php
> +	'ACP_HELP_PHPBB'			=> 'Unterstütze phpBB',
Das sollte in der "Sie" Variante aber "Unterstützen Sie phpBB" heißen.

2016-12-11 17:59 UTC, Philipp-K commented on language/de/acp/common.php
> +	'UPDATE_NEEDED'			=> 'Das Board ist nicht auf dem neusten Stand.',
Wenn ich da so rüberlese: wäer "Die Board-Software ist..." nicht besser?

2016-12-11 17:59 UTC, Philipp-K commented on language/de/acp/common.php
> +	'FAIL_SEND_STATISTICS'		=> 'phpBB konnte die Statistiken nicht senden',
Hier würde ich einfach "Die Statistiken konnten nicht gesendet werden" schreiben

2016-12-11 18:37 UTC, gn36 approved these changes

2016-12-13 19:29 UTC, Philipp-K commented on language/de/acp/common.php
> +	'UPDATE_NEEDED'			=> 'Die Board-Software ist nicht auf dem neusten Stand.',
Wir haben bislang immer "neu**e**sten" verwendet - betrifft auch die kommende Zeile

2016-12-13 21:30 UTC, Philipp-K approved these changes
Aus meiner Sicht OK

2016-12-14 19:27 UTC, gn36 approved these changes

2016-12-14 19:27 UTC, merged