Translation/changes for cli.php, common.php and install Part 2
phpbb-de/phpbb-translation pull request #312
Opened 2016-12-11 14:12 UTC by Crizz0

cli.php
common.php
install.php

Part 2

#310

2016-12-11 17:49 UTC, gn36 requested changes
Ich hoffe ich habe da ansonsten nichts übersehen.

2016-12-11 17:49 UTC, gn36 commented on language/de/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung deiner phpBB-Installation nicht vollständig durchgeführt wurde. Besuche die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stell sich
Statt "Besuche die Datenbank-Aktualisierung würde ich "Rufe die Datenbank-Aktualisierung auf" schreiben (das ist nur meine Meinung, kein wirklicher Fehler)

>stell sicher,

ist aber in meinen Augen falsch, das muss "stelle sicher" lauten.

>und klicke auf <strong>Absenden</strong>

da würde ich noch ein "dann" oder "danach" einfügen:
>und klicke dann auf <strong>Absenden</strong>

Inhaltlich: Wann kommt der Hinweis? Ist der "Install" Ordner da zwingend vorhanden? Ansonsten sollte vielleicht noch ein Hinweis rein, dass man den erst mal (wieder) reinkopieren muss bevor man ihn entfernt. Da es außerdem um ein Update geht würde ich davon ausgehen, dass der Ordner schon mal weg war, daher gehört in meinen Augen ein "wieder" in den letzten Satz hinein.

2016-12-11 17:49 UTC, gn36 commented on language/de_x_sie/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_OPTION_STABILITY'	=> 'Führe den „check“-Befehl mit der Auswahl „stable“- oder „unstable“-Versionen aus.',
Ich glaube die Formulierung passt nicht zu unseren bisherigen Beschreibungen. "Führe den Befehl aus" beschreibt nicht direkt den Befehl. Besser passt imho "Führt den Befehl aus", also z.B. "Führt den 'check' Befehl mit Cache aus". Das betrifft auch die "du" Version.

So oder so wäre das in der Form auch nicht für de_x_sie tauglich, dafür müsste es sonst "Führen Sie den Befehl aus" heißen.

2016-12-11 17:49 UTC, gn36 commented on language/de_x_sie/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung Ihrer phpBB-Installation nicht vollständig durchgeführt wurde. Besuchen Sie die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stelle
Hier gilt natürlich das gleiche wie in der "du" Version.

2016-12-11 17:49 UTC, gn36 commented on language/de/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Version.',
Hier geht es nicht um Version sondern Stabilität. In meinen Augen wäre also korrekt:

> "%s" ist keine gültige Stabilitätsangabe.

Original: 
> "%s" is not a valid stability.

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_OPTION_CACHE'		=> 'Führe den „check“-Befehl mit Cache aus.',
Evtl. auch "Führt den Befehl auf Basis des Caches/der im Cache gespeicherten Informationen durch"

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_ARGUMENT_1'		=> 'Name der zu überprüfenden Erweiterung (bei „all“, werden alle Erweiterungen überprüft)',
Das Komma nach all muss weg

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_OPTION_STABILITY'	=> 'Führe den „check“-Befehl mit der Auswahl „stable“- oder „unstable“-Versionen aus.',
Ermöglicht, die Prüfung auf stabile Versionen ("stable") oder Entwicklungsversionen ("unstable") zu begrenzen

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Version.',
Die Anführungszeichen müssten noch angepasst werden

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE'				=> 'Ihre phpBB-Installation wurde nicht richtig aktualisiert.',
konnte nicht richtig aktualisiert werden?

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE_MORE'		=> 'Bitte lesen Sie sich die folgenden Information durch, um diesen Fehler zu beheben.',
Das "sich" würde ich rausnehmen

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung Ihrer phpBB-Installation nicht vollständig durchgeführt wurde. Besuchen Sie die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stelle
"Wir haben bemerkt" findet ich etwas komisch. Besser gleich anfangen mit "Die letzte Aktualisierung..."
Ferner müssten beim Verzeichnisnamen noch die Anführungszeichen angepasst werden.

2016-12-11 17:59 UTC, Philipp-K commented on language/de_x_sie/install.php
> +	'TASK_INSTALL_EXTENSIONS'	=> 'Installiere gepackte Erweiterungen',
Installiere Erweiterungs-Pakete?

2016-12-11 18:36 UTC, Crizz0 commented on language/de/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung deiner phpBB-Installation nicht vollständig durchgeführt wurde. Besuche die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stell sich
Der Hinweis wird im ACP > System angezeigt. Dort wo die Versionsanzeige ist und dort wird man dann auf "Update database" verlinkt, was natürlich nicht geht, wenn der "install"-Ordner fehlt.

2016-12-11 18:38 UTC, Crizz0 commented on language/de/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Version.',
Das fand ich irgendwie nicht so verständlich. Und da ich es eine Zeile weiter oben mit 
>  „stable“- oder „unstable“-Versionen

bezeichnet habe, fand ich das passend.

2016-12-11 18:40 UTC, Crizz0 commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE'				=> 'Ihre phpBB-Installation wurde nicht richtig aktualisiert.',
Macht irgendwie keinen Unterschied.

2016-12-11 18:41 UTC, gn36 commented on language/de/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung deiner phpBB-Installation nicht vollständig durchgeführt wurde. Besuche die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stell sich
Ok, vielleicht sollten wir das phpBB.com für die englische Version dann auch als Änderung vorschlagen (natürlich dann für die Final / den nächsten RC). 

Meinetwegen lassen wir es dann vorerst so wie das Original.

2016-12-11 18:41 UTC, Crizz0 commented on language/de_x_sie/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung Ihrer phpBB-Installation nicht vollständig durchgeführt wurde. Besuchen Sie die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stelle
Japp, der Einstieg in 1. Person Plural ist ein wenig ungewöhnlich, so sieht es im Original allerdings aus. Können wir gerne freier machen.
@gn36  Was meinst du?

2016-12-11 18:44 UTC, Crizz0 commented on language/de_x_sie/install.php
> +	'TASK_INSTALL_EXTENSIONS'	=> 'Installiere gepackte Erweiterungen',
Ich weiß nicht genau, wo das wie eingeblendet wird und was "Packaged extensions" sein sollen. Das wäre hier vmtl. hilfreich.

2016-12-11 18:51 UTC, gn36 commented on language/de/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Version.',
Hm. Ich finde "Version" verwirrend, weil man dann denken könnte, dass eine konkrete Versionsangabe wie "1.0.2" gefordert ist. In der Zeile drüber passt Version, weil es um stabile oder instabile Versionen geht. Das beschreibt dann aber trotzdem noch die Stabilität der Versionen und nicht die Version selbst. In dieser Zeile ist das anders. Wenn dir Stabilität ansich nicht gefällt, dann vielleicht stattdessen:
> Versionsstabilität

Meinetwegen auch:
> Versionsstabilitätsangabe

Oder wir listen notfalls die gültigen Werte "stable" und "unstable" auf.

Jetzt wo ich mir die beiden Zeilen drüber noch mal ansehe gefallen mir die Cache Zeile auch nicht mehr wirklich. Ich fände für die Cache Geschichte "Führt den "check"-Befehl unter Nutzung des Caches aus." besser.

Beide Zeilen drüber brauchen natürlich den Umbau "Führe aus" -> "Führt aus"

2016-12-11 18:56 UTC, gn36 commented on language/de_x_sie/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung Ihrer phpBB-Installation nicht vollständig durchgeführt wurde. Besuchen Sie die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stelle
Die DE Übersetzung war immer schon in Details etwas unpersönlicher als die Englische Variante. Ich finde Philipps Vorschlag besser als die aktuelle Version, einen guten Alternativvorschlag habe ich nicht.

2016-12-11 18:57 UTC, gn36 commented on language/de/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Version.',
Alternativ siehe PhilippKs Version.

2016-12-11 18:59 UTC, gn36 commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE'				=> 'Ihre phpBB-Installation wurde nicht richtig aktualisiert.',
Hm, richtig => vollständig? Ob nun "konnte" oder nicht ist mir egal, ich denke wir nutzen "Konnte" aber häufiger.

2016-12-11 18:59 UTC, gn36 commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE_MORE'		=> 'Bitte lesen Sie sich die folgenden Information durch, um diesen Fehler zu beheben.',
:+1:

2016-12-11 19:01 UTC, Crizz0 commented on language/de/install.php
> +		<p>Wir haben bemerkt, dass die letzte Aktualisierung deiner phpBB-Installation nicht vollständig durchgeführt wurde. Besuche die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a>, stell sich
Dazu können wir gerne in Ticket erstellen, es ist halt nicht zu sagen, ob "install" noch da ist oder schon weg. Nachdem Update kommt man immerhin auch erstmal ins ACP. Von daher würde ich da jetzt nicht ganze Sätze dazu dichten.

2016-12-11 19:18 UTC, Crizz0 commented
Wieso ist das von @gn36 alles 4mal da?

2016-12-11 19:20 UTC, gn36 commented
Das habe ich mich auch schon gefragt. Wenn du die Seite neu lädst ist das aber nicht mehr so. Ich vermute mal das ist ein Bug in dem Github Review Tool.

2016-12-11 19:26 UTC, gn36 commented on language/de_x_sie/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_OPTION_STABILITY'	=> 'Führt den „check“-Befehl mit der Auswahl „stable“- oder „unstable“-Stabilität aus.',
"Version" in dieser Zeile war schon in Ordnung. Nur drunter nicht. Wenn du es gleich haben willst dann vielleicht besser
> Führt den "check"-Befehl wahlweise mit der Stabilität "stable" oder "unstable" aus.

2016-12-11 19:32 UTC, Crizz0 commented on language/de_x_sie/install.php
> +	'UPDATE_INCOMPLETE'				=> 'Ihre phpBB-Installation wurde nicht richtig aktualisiert.',
Da meinstens ein Benutzerfehler vorliegt, würde ich da schon gerne bei der direkten Variante bleiben. Aber "vollständig" finde ich gut.

2016-12-11 19:32 UTC, Crizz0 commented on language/de/install.php
> +	'DATABASE_VERSION'		=> 'Databankversion',
Datenbankversion oder Datenbank-Version?

2016-12-11 19:35 UTC, gn36 commented on language/de/install.php
> +	'DATABASE_VERSION'		=> 'Databankversion',
Da alles andere mit Bindestrich abgetrennt ist würde ich das hier auch so machen (aber ersetz' auf jeden Fall auch das Data durch Daten ;) ), auch wenn zusammenschreiben in allen Fällen vermutlich richtiger wäre ist so der Unterschied der Textfelder einfacher zu erkennen.

2016-12-12 20:26 UTC, Crizz0 commented on language/de_x_sie/install.php
> +	'TASK_INSTALL_EXTENSIONS'	=> 'Installiere gepackte Erweiterungen',
Ich hab mich mal durchgefragt, dass wird bei der frischen Installation eingeblendet, während gerade die (im Komplettpaket befindliche) Extension "Viglink" installiert wird. 
Vielleicht: 
"Installiere vorhandene Erweiterungen"

2016-12-12 21:39 UTC, gn36 commented on language/de_x_sie/install.php
> +	'TASK_INSTALL_EXTENSIONS'	=> 'Installiere gepackte Erweiterungen',
Da ist "packaged" dann eher mit "mitgeliefert" zu übersetzen würde ich sagen.

2016-12-12 21:41 UTC, gn36 commented on language/de/cli.php
>  	'CLI_ERROR_INVALID_STABILITY' => '„%s“ ist keine gültige Version.',
Hier ist aber immer noch "Version" statt Stabilität...

2016-12-12 21:41 UTC, gn36 commented on language/de_x_sie/cli.php
>  	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Stabilität.',
Hier natürlich auch.

2016-12-13 13:58 UTC, Crizz0 commented on language/de_x_sie/cli.php
>  	'CLI_ERROR_INVALID_STABILITY' => '"%s" ist keine gültige Stabilität.',
Äh, ne? 😇

2016-12-13 19:35 UTC, Philipp-K commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK'					=> 'Prüft, ob das Board auf dem neusten Stand ist.',
auch hier "neuesten"

2016-12-13 19:35 UTC, Philipp-K commented on language/de/install.php
> +		<p>Die letzte Aktualisierung deiner phpBB-Installation wurde nicht vollständig durchgeführt. Rufe die <a href="%1$s" title="%1$s">Datenbank-Aktualisierung</a> auf, stelle sicher, dass <em>Nur die D
Nach "nicht" ein Komma?

2016-12-13 19:35 UTC, Philipp-K commented on language/de/cli.php
> +	'CLI_ERROR_INVALID_STABILITY' => '„%s“ ist keine gültige Version.',
Irgendwie ist das noch nicht mein bester Freund :-?

2016-12-13 21:40 UTC, Philipp-K commented
Jemand eine bessere Idee für "Führt den „check“-Befehl wahlweise mit der Stabilität „stable“ oder „unstable“ aus."?

2016-12-14 19:52 UTC, gn36 commented
Hm. "check"-Befehl muss eigentlich so bleiben, weil der Befehl nun mal auf Englisch eingegeben wird. Das ganze ist ja für die Prüfung, ob Updates da sind oder nicht. Mit der Wahl "stable" werden nur stabile Versionen der Erweiterung / von phpBB berücksichtigt, bei der Wahl "unstable" auch Entwicklungsversionen. Ist eine Entwicklungsversion installiert, werden immer Entwicklungsversionen berücksichtigt (zumindest wenn der Mechanismus noch so ist wie bei 3.1, wovon ich ausgehen würde). Wenn die Sprachvariable dargestellt wird ist imho die Angabe der Befehlsbezeichnung überflüssig, weil es sich um eine Option des Befehls handelt. Daher würde in meinen Augen auch die folgende Übersetzung gehen, ähnlich wie du das schon vorgeschlagen hattest:
> Nur stabile ("stable") oder auch Entwicklungsversionen ("unstable") berücksichtigen

Das ganze wird ja nur angezeigt, wenn man sich die Hilfe zum update:check Befehl anzeigen lässt, da ist der Kontext imho klar.

In einer 80 Zeichen Konsole wird der Text bei mehr als 50 Zeichen Beschreibung umgebrochen (bei diesem Befehl, bei anderen ggf. anders), wenn möglich sollten wir also kurze und prägnante Beschreibungen haben.

2016-12-14 21:01 UTC, Crizz0 commented
Wie wäre es so: 
> "Nur auf produktive ("stable") oder vorläufige Versionen ("unstable") prüfen"

2016-12-15 10:42 UTC, gn36 commented
Auch ok 

Am 14. Dezember 2016 22:01:46 MEZ, schrieb Christian Schnegelberger <notifications@github.com>:
>Wie wäre es so: 
>> "Nur auf produktive ("stable") oder vorläufige Versionen ("unstable")
>prüfen"
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb-de/phpbb-translation/pull/312#issuecomment-267155487

2016-12-17 20:52 UTC, Philipp-K approved these changes
Ich finde nichts mehr

2016-12-17 21:03 UTC, gn36 approved these changes

2016-12-17 21:03 UTC, gn36 commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_CHECK_OPTION_CACHE'		=> 'Führt den Befehl („check“) auf Basis der im Cache gespeicherten Informationen aus.',
Naja wie gesagt steht das in der Hilfe zum Befehl, ich finde das "check" auch in Klammern überflüssig ;)

Wenn du willst kannst du es aber auch so lassen.

2016-12-17 21:19 UTC, Crizz0 commented
Das liest sich halt ohne die check Angabe ein wenig seltsam, deshalb hab ich drin gelassen. Dann haben wir da den gleichen Infogehalt wie in "en"

2016-12-17 21:26 UTC, merged