Changes in migrator.php and ucp.php for 3.2.0-RC2 PART 3
phpbb-de/phpbb-translation pull request #313
Opened 2016-12-11 14:35 UTC by Crizz0

migrator.php
ucp.php

Part 1: #311 
Part 2: #312 
Part 3: this PR

#310

2016-12-11 17:53 UTC, gn36 requested changes
Für de_x_sie gilt natürlich das gleiche.

2016-12-11 17:53 UTC, gn36 commented on language/de/migrator.php
>  	'MIGRATION_REVERT_SCHEMA_RUNNING'	=> 'Mache Schema-Änderungen rückgängig: %s.',
Das passt nicht zu den bisherigen Ausdrücken: In meinen Augen müsste das 
> Mache Schema-Änderungen rückgängig: ....

heißen.

2016-12-11 17:53 UTC, gn36 commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen; Breite: %1$s, Höhe: %2$s.',
Evtl. Doppelpunkt statt Semikolon?

2016-12-11 17:58 UTC, Philipp-K commented on language/de/migrator.php
> +	'MIGRATION_REVERT_SCHEMA_IN_PROGRESS'	=> 'Rückgängig machen von Schema-Änderungen: %1$s; Dauer: %2$.2f Sekunden',
Mache Schema-Änderungen rückgängig (wie drei Zeilen weiter oben)

2016-12-11 17:58 UTC, Philipp-K commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen; Breite: %1$s, Höhe: %2$s.',
Doppelpunkt statt Strichpunkt

2016-12-13 19:38 UTC, Philipp-K commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen: Breite: %1$s, Höhe: %2$s.',
Sollten wir da nicht einheitlich "Abmessungen" oder "Größe" für beides verwenden?

2016-12-13 19:47 UTC, Crizz0 commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen: Breite: %1$s, Höhe: %2$s.',
Lieber nicht, denn dann wird es wieder verwechselt. Zeile 144 geht nur um die Maße und bei No. 143 ist die Dateigröße (KB, MB) zusätzlich gemeint.

2016-12-13 21:28 UTC, Philipp-K commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen: Breite: %1$s, Höhe: %2$s.',
Wenn ich das richtig verstehe, wird das zweite nur verwendet, wenn keine maximale Dateigröße festgelegt wurde.

Aus meiner Sicht geht "Maximale Größe" für beides. Alternativ wäre möglich:
- Maximale Abmessungen: Breite: %1$s, Höhe: %2$s, maximale Dateigröße: ...

2016-12-13 21:35 UTC, Crizz0 commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Abmessungen: Breite: %1$s, Höhe: %2$s.',
Die Alternative halte ich für brauchbar. :)

2016-12-15 20:42 UTC, Philipp-K commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN'				=> 'Maximale Abmessungen: Breite: %1$s, Höhe: %2$s, maximale Dateigröße: %3$.2f KiB.',
Kleinigkeit: vor "Dateigröße" würde ich statt dem Komma einen Strichpunkt nutzen

2016-12-16 22:10 UTC, Crizz0 commented
@gn36 Hast du hier noch was? Zumindest will das System noch Änderungen durch dich.

2016-12-17 20:43 UTC, Philipp-K approved these changes
Aus meiner Sicht passt alles

2016-12-17 20:47 UTC, Philipp-K commented
gn36 hat auf Zeile 64 alt (MIGRATION_REVERT_SCHEMA_RUNNING) kommentiert - die ist (richtigerweise) unverändert, so dass das immer noch als offen gezählt wird

2016-12-17 20:59 UTC, gn36 approved these changes

2016-12-17 20:59 UTC, merged