VigLink Übersetzung integriert
phpbb-de/phpbb-translation pull request #315
Opened 2016-12-29 20:40 UTC by gn36

VigLink Übersetzung integriert unter ext/

Ggf. sind Änderungen an der build.xml oder der travis config erforderlich, bitte den travis Bericht genau durchsehen, bevor da irgendwas gemergt wird.

Fixes #314

2016-12-29 20:57 UTC, gn36 commented
Ok, ich habe das lokal mal etwas ausführlicher getestet und gezielt Fehler provoziert, die neuen Dateien werden korrekt mitgetestet und auch mit in die Pakete integriert.

2016-12-30 18:06 UTC, Crizz0 commented
Ich habe gerade die Ankündigung an die Übersetzer veröffentlicht, wir werden die Übersetzung im "ext/"-Ordner ergänzen dürfen/müssen.

2016-12-30 18:15 UTC, Crizz0 requested changes

2016-12-30 18:15 UTC, Crizz0 commented on ext/phpbb/viglink/language/de/info_acp_viglink.php
> + *
```
* Deutsche Übersetzung durch die Übersetzer-Gruppe von phpBB.de:
* siehe language/de/AUTHORS.md und https://www.phpbb.de/go/ubersetzerteam
```

Sollte noch ergänzt werden im Dateikopf.

2016-12-30 18:15 UTC, Crizz0 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
"monetarisiert" klingt schon krass umständlich. Jemand noch eine bessere Idee? 

Für "Nutzererlebnis" vielleicht "ohne in der Wahrnehmung der Nutzer..." Weil man sieht es den Links erst beim Click an, zumindest für Nicht-Laien.

2016-12-30 18:15 UTC, Crizz0 commented on ext/phpbb/viglink/language/de_x_sie/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruchen Sie Ihre Erträge',
Verdienste? Einnahmen? (statt Erträge)

2016-12-31 15:39 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Ich hatte da glaube ich bei Martin was reinkommentiert und einen anderen Vorschlag geschrieben. Vielleicht hat den Martin noch im Zugriff

2016-12-31 15:50 UTC, Philipp-K requested changes

2016-12-31 15:50 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
So, den Kommentare wieder gefunden - nur da hatte ich auch "monetarisiert" verwendet...
Nutzererlebnis kam übrigens durch den Wikipedia-Eintrag zu "User Experience".

Anderer Vorschlag für monetarisiert: "der aus von deinen Benutzern erstellten Links Geld generiert".

2016-12-31 15:50 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_EARNINGS_EXPLAIN'  => 'Du kannst die durch dein Forum generierten Erträge selbst beanspruchen, indem du einen eigenen VigLink Account erstellst.',
VigLink-Account (Bindestrich)

2016-12-31 15:50 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_DISABLED_PHPBB'	=> 'Die VigLink Dienste wurden von phpBB deaktiviert.',
Die VigLink-Dienste wurden von phpBB.com deaktiviert.

2016-12-31 15:50 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM_EXPLAIN'		=> 'Du kannst die in deinem Forum aus den von VigLink monetarisierten Links generierten Erträge beanspruchen anstatt sie dem phpBB Projekt zu überlassen. Um deine Accoun
Du kannst die in deinem Forum **über** VigLink generierten Erträge beanspruchen**,** anstatt sie dem phpBB**-**Projekt zu überlassen. Um deine Accounteinstellungen zu verwalten**,** erstelle deinen eigenen „VigLink Convert“ Account, indem du auf „Convert Account“ klickst'

2016-12-31 15:50 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_NO_CONVERT_LINK'	=> 'Der VigLink Convert Account Link konnte nicht abgerufen werden.'
Auch noch nicht ideal

2016-12-31 19:59 UTC, Joyce-Luna commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Ich finde nicht jeder weiß was das Wort "monetarisiert" bedeutet. Ich bin der Meinung ihr solltet davon ganz weg gehen. Der ersten Satz könnte in etwa auch so aussehen.

VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links an Waren- oder an Dienstleistungen weiterleitet, ohne das es sich auf das Nutzungserlebnis aus wirkt.

2016-12-31 20:04 UTC, Joyce-Luna commented on ext/phpbb/viglink/language/de_x_sie/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruchen Sie Ihre Erträge',
Gewinne?

2017-01-01 14:41 UTC, gn36 commented on ext/phpbb/viglink/language/de_x_sie/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruchen Sie Ihre Erträge',
Hm, von den Alternativen gefällt mir Einnahmen am besten.

2017-01-01 14:53 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Monetarisiert gefiel mir auch nicht. Aber wenn wir uns vom original entfernen, dann sollten wir finde ich genauer beschreiben, was passiert. Viglink leitet ja nicht weiter, sondern modifiziert per JS die links und fügt z.b. eine ID ein, so dass über affiliate Programme o.ä. Geld abgegriffen wird, zumindest wenn ich das richtig verstehe. 

So richtig beschreibt das aber keine der alternativen und ich finde es auch schwierig, das ohne ausufernden Text hinzukriegen. 

Philipps Alternative gefällt mir noch am besten bisher, trifft den Kern aber auch nicht. 
Der Text ist übrigens schon dein Alternativvorschlag, meine Variante klang noch etwas anders.

Bzgl Nutzererlebnis evtl "für Benutzer unsichtbar" oder sowas?

2017-01-01 15:05 UTC, Joyce-Luna commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Ihr müsst aber das ganze auch so beschreiben, das es jeder verstehen kann. Nicht jeder hat ein Fremdwörter Lexikon verschluckt :)
Es sollte für jeden direkt verständlich sein ohne danach googln zu müssen. 
Vielleicht kann man aber einen Link setzen der zu einer Ausführlichen Erklärung führt. Das auf Englisch und auf Deutsch.

2017-01-02 18:53 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Die Erklärung steht ja schon dahinter, was genau passiert: 
>Wenn Besucher auf diese Links klicken und auf der Ziel-Website zum Beispiel Waren oder Dienstleistungen einkaufen, dann zahlen einige Händler VigLink eine Provision.

Von daher könnten wir in meinen Augen auch aus "der von Benutzern deines Forums erstellte Links monetarisiert" einfach folgendes machen:

> der von Benutzern deines Forums erstellte Links geringfügig verändert

vollständig dann:
> VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links geringfügig verändert oder ergänzt, ohne dass sich die Zielseite des Links verändert.

Alternativ ziemlich weit weg vom Original:
> VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links um Trackinginformationen ergänzt, ohne dass sich das Ziel des Links verändert.

2017-01-02 18:57 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_NO_CONVERT_LINK'	=> 'Der VigLink Convert Account Link konnte nicht abgerufen werden.'
Mit Bindestrichen?

2017-01-02 19:00 UTC, gn36 commented on ext/phpbb/viglink/language/de_x_sie/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruchen Sie Ihre Erträge',
@Philipp-K  was meinst du?

2017-01-02 19:02 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_DISABLED_PHPBB'	=> 'Die VigLink Dienste wurden von phpBB deaktiviert.',
Naja, korrekt wäre wohl eher "phpBB Limited" oder?

2017-01-02 19:45 UTC, Philipp-K requested changes
Ich bin das ganze nochmals durchgegangen und habe mich auch mal etwas tiefer bei VigLink eingelesen. Der Dienst heißt "VigLink Convert" - siehe auch http://www.viglink.com/products/ und http://www.vermarktercheck.de/anbieter/viglink/

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_DISABLED_PHPBB'	=> 'Die VigLink Dienste wurden von phpBB deaktiviert.',
Jo

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Next try: VigLink ist ein externer Affiliate-Dienst, der Provisionen aus Links generiert, die Benutzer in deinem Forum erstellen. Dazu werden die Links um Tracking-Informationen von VigLink ergänzt, ohne dass sich für den Benutzer beim Aufruf des Links etwas ändert (VigLink Convert). Wenn Besucher auf der Ziel-Website zum Beispiel Waren oder Dienstleistungen einkaufen, dann zahlen einige Händler VigLink eine Provision. Hiervon wird ein Anteil an das phpBB-Projekt weitergegeben. Indem du der Verwendung von VigLink und der Weitergabe der Provision an phpBB Limited zustimmst, unterstützt du das Open-Source-Projekt und trägst zu seiner finanziellen Absicherung bei.

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de_x_sie/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruchen Sie Ihre Erträge',
Ich würde erst mal alles unter "Du" diskutieren - auch weil es durchaus ein paar Abhängigkeiten gibt :-)

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM'				=> 'Beanspruche deine Erträge',
Alternativ: "Eigene Provisionen beanspruchen" oder "Provisionen selbst beanspruchen" (siehe unten)

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM_EXPLAIN'		=> 'Du kannst die in deinem Forum aus den von VigLink monetarisierten Links generierten Erträge beanspruchen anstatt sie dem phpBB Projekt zu überlassen. Um deine Accoun
Dann hier auch "phpBB Limited" und ggf. auch "Provisonen"

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_API_KEY_INVALID'	=> '„%s“ ist kein gültiger VigLink Convert API Schlüssel.',
„%s“ ist kein gültiger API Schlüssel für VigLink Convert

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CONVERT_ACCOUNT'	=> 'Convert Account',
Ich würde hier (und dann auch bei ACP_VIGLINK_CLAIM_EXPLAIN) von "VigLink Convert-Account" (oder -Konto) sprechen.

2017-01-02 19:45 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_NO_CONVERT_LINK'	=> 'Der VigLink Convert Account Link konnte nicht abgerufen werden.'
Der Account-Link von VigLink Convert konnte nicht abgerufen werden (oder -Konto)

2017-01-04 20:15 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SETTINGS_EXPLAIN'	=> 'VigLink ist ein externer Dienst, der von Benutzern deines Forums erstellte Links monetarisiert, ohne sich auf das Nutzungserlebnis auszuwirken. Wenn Besucher auf d
Hm, irgendwie wurde ich nicht über die Antwort informiert :(

Die neue Version gefällt mir besser, ich würde sie aber geringfügig abwandeln:
> Dazu werden die Links von VigLink um Tracking-Informationen ergänzt.

(Reihenfolge geändert - mir ist nicht klar ob die Trackinginfos von Viglink sind oder ob direkt Affiliate Links z.B. von Amazon generiert werden, die andere Reihenfolge passt aber für beides).

2017-01-04 20:26 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_NO_CONVERT_LINK'	=> 'Der VigLink Convert Account Link konnte nicht abgerufen werden.'
Wollen wir das blöde "Convert" vielleicht einfach weglassen in dem Fall? Die Wichtige Info ist doch, dass das mit dem Link nicht geklappt hat.

2017-01-04 20:34 UTC, gn36 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM_EXPLAIN'		=> 'Du kannst die in deinem Forum aus den von VigLink monetarisierten Links generierten Erträge beanspruchen anstatt sie dem phpBB Projekt zu überlassen. Um deine Accoun
Dann setze ich erst mal "Provisionen" ein.

2017-01-04 20:37 UTC, gn36 commented on ext/phpbb/viglink/language/de/info_acp_viglink.php
> + *
Ist jetzt drin

2017-01-04 22:25 UTC, Crizz0 approved these changes

2017-01-05 08:29 UTC, Philipp-K requested changes
Bis auf die Kleinigkeiten OK

2017-01-05 08:29 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_API_KEY_INVALID'	=> '„%s“ ist kein gültiger API Schlüssel für VigLink Convert.',
API-Schlüssel

2017-01-05 08:29 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_DISABLED_PHPBB'	=> 'Die VigLink Dienste wurden von phpBB Limited deaktiviert.',
VigLink-Dienste

2017-01-05 08:29 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM_EXPLAIN'		=> 'Du kannst die in deinem Forum über VigLink generierten Provisionen beanspruchen, anstatt sie phpBB Limited zu überlassen. Um deine Accounteinstellungen zu verwalten,
Müsste das nicht korrekterweise mit einem Punkt enden?

2017-01-05 08:29 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_CLAIM_EXPLAIN'		=> 'Du kannst die in deinem Forum über VigLink generierten Provisionen beanspruchen, anstatt sie phpBB Limited zu überlassen. Um deine Accounteinstellungen zu verwalten,
Evtl. auch "selbst" beanspruchen

2017-01-06 22:16 UTC, Philipp-K approved these changes

2017-01-06 22:19 UTC, merged