Updates composer.json and composer.lock for composer usage
phpbb-de/phpbb-translation pull request #326
Opened 2017-01-16 20:47 UTC by Crizz0

Fix #325

2017-01-16 20:57 UTC, Crizz0 commented on composer.json
> +	"version": "3.1.11-dev",
Evtl. sogar unnötig: https://getcomposer.org/doc/04-schema.md 

Muss ich mir nochmal überlegen. Kann er ja immer aus dem Release-Tag ziehen.

2017-01-16 21:01 UTC, Crizz0 commented
Ich überlege, ob ich noch folgenden Felder ergänze:

```
"support": {
		"issues": "https://github.com/phpbb-de/phpbb-translation/issues",
		"forum": "https://www.phpbb.de/community/",
},
```
und:
```
"authors": [
		{
			"name": "phpBB Deutschland e. V.",
			"email": "webmaster@phpbb.de",
			"homepage": "https://www.phpbb.de/go/ubersetzerteam"
		}
],
```
ergänzen soll, was meint ihr?

2017-01-17 16:04 UTC, Philipp-K commented
Greift das für alle Branches? Wenn nein, währe die Version im Title ("... für phpBB 3.1") evtl. hilfreich.

2017-01-17 18:22 UTC, Crizz0 commented
@Philipp-K: Das wird für alle branches ergänzt und nach oben gemerged. Dann natürlich mit einer anderen Versionsnummer.

2017-01-17 18:44 UTC, bantu requested changes

2017-01-17 18:44 UTC, bantu commented on composer.json
> +	"version": "3.1.11-dev",
?

2017-01-17 18:44 UTC, bantu commented on composer.json
> +	"time": "2017-01-16",
?

2017-01-17 18:45 UTC, Crizz0 commented on composer.json
> +	"time": "2017-01-16",
Ich bin nicht sicher, ob das da rein muss. Eher nicht?

2017-01-17 18:46 UTC, Crizz0 commented on composer.json
> +	"version": "3.1.11-dev",
Ich dachte wir schreiben dort nur bei einem release-tag die richtige Version rein, zu der es gehört z.B. phpBB 3.1.11 und lassen in dem branch, wo ständig was gepatcht wird, einen "-dev" Marker. Spricht da was gegen?

2017-01-17 18:47 UTC, bantu commented on composer.json
> +	"time": "2017-01-16",
Ist das denn im Schema von Composer definiert?

2017-01-17 18:48 UTC, bantu commented on composer.json
> +	"version": "3.1.11-dev",
Dafür ist das Git repository da. Tags erzeugen Versionen.

2017-01-17 18:49 UTC, Crizz0 commented on composer.json
> +	"time": "2017-01-16",
Ja: https://getcomposer.org/doc/04-schema.md#time

2017-01-17 18:51 UTC, Crizz0 commented on composer.json
> +	"version": "3.1.11-dev",
Laut der Info: https://getcomposer.org/doc/04-schema.md kann man das weglassen, steht die Nummer ja auch noch in der Readme. Steht hier als "optional" bzw. entbehrlich, wenn man die Nummer auch von den tags herbekommt: https://getcomposer.org/doc/04-schema.md#version 

Habe mich aber an den .com-exts orientiert, die nutzen "version": noch.

2017-01-17 18:56 UTC, bantu commented on composer.json
> +	"version": "3.1.11-dev",
Würde Tags nutzen und das auch in der Readme nicht aufführen.

2017-01-17 18:58 UTC, Crizz0 commented on composer.json
> +	"version": "3.1.11-dev",
Die Angabe in der Readme hatte ich noch immer als ganz brauchbar gehalten, um mal auf einen Blick zu sehen für welche Version das Paket so ist, wenn es Probleme gibt.

2017-01-17 19:00 UTC, bantu commented on composer.json
> +	"version": "3.1.11-dev",
Jo, ok, für manuelle Installation macht das wohl Sinn.

2017-01-17 19:06 UTC, Crizz0 commented on composer.json
> +	"version": "3.1.11-dev",
Ist natürlich mühsam, das immer nachzupflegen, haben wir bei 3.2.0 auch glatt vergessen.

2017-01-17 20:33 UTC, gn36 commented
Kann nicht schaden. Wie sollten dann aber mal die Übersetzer Liste korrigieren. Aktuell ist da nur Philipp drin.

Am 16. Januar 2017 22:01:41 MEZ schrieb Christian Schnegelberger <notifications@github.com>:
>Ich überlege, ob ich noch folgenden Felder ergänze:
>
>```
>"support": {
>		"issues": "https://github.com/phpbb-de/phpbb-translation/issues",
>		"forum": "https://www.phpbb.de/community/",
>},
>```
>und:
>```
>"authors": [
>		{
>			"name": "phpBB Deutschland e. V.",
>			"email": "webmaster@phpbb.de",
>			"homepage": "https://www.phpbb.de/go/ubersetzerteam"
>		}
>],
>```
>ergänzen soll, was meint ihr? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb-de/phpbb-translation/pull/326#issuecomment-272961189

2017-01-17 20:46 UTC, gn36 commented
Ich glaube die Empfehlung ist, die Version ganz weg zu lassen, zumindest seitens composer/packagist. Aus den Tags geht die Version ja eindeutig hervor. 

Vorteil wenn wir die dev Version drin lassen wäre, dass immer ein grober Versionsstand drin steht. Halte ich aber nicht wirklich für wichtig. Wenn von phpbb  die Version gefordert wird könnten wir die auch automatisch beim Release rein schreiben mit dem build Skript. Ich habe aber nicht geschaut, ob der Validator das prüft, wenn müssten wir ggf. den noch austricksen. 

Am 17. Januar 2017 19:46:47 MEZ schrieb Christian Schnegelberger <notifications@github.com>:
>Crizz0 commented on this pull request.
>
>
>
>> @@ -1,6 +1,25 @@
> {
>+	"name": "phpbb-de/phpbb-translation",
>+	"description": "German Translation of phpBB",
>+	"type": "phpbb-language",
>+	"homepage": "https://github.com/phpbb-de/phpbb-translation",
>+	"version": "3.1.11-dev",
>
>Ich dachte wir schreiben dort nur bei einem release-tag die richtige
>Version rein, zu der es gehört z.B. phpBB 3.1.11 und lassen in dem
>branch, wo ständig was gepatcht wird, einen "-dev" Marker. Spricht da
>was gegen? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb-de/phpbb-translation/pull/326

2017-01-17 20:52 UTC, Crizz0 commented
phpbb verlangt das afaik nicht.

2017-01-17 21:21 UTC, Philipp-K requested changes

2017-01-17 21:21 UTC, Philipp-K commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Sollten wir da nicht in die Übersetzungsforen linken (idealerweise per go)

2017-01-17 21:34 UTC, Crizz0 commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Das passt irgendwie nicht zum Label. Ich würde das so allgemein behalten wollen.

2017-01-17 21:36 UTC, Philipp-K commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Na ja, es geht ja um Support für die Sprachdateien - da ist der Verweis auf die ganze Community schon etwas hochgegriffen.

2017-01-18 08:21 UTC, gn36 commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Für die issues finde ich den Verweis auf Github in Ordnung.

Was die Foren angeht: Letztlich kommt es in meinen Augen auf das Problem an: Wenn der Nutzer ein Problem mit der Installation hat, für welches er Support benötigt, ist der Verweis auf die allgemeinen Foren schon richtig (oder genauer eben das Support Forum und nicht allgemein community). Wenn es um Fehler in den Sprachpaketen geht: Entweder Github, oder eben die Sprachforen. Ich finde den pauschalen Verweis auf die Supportforen daher nicht falsch.

2017-01-18 08:29 UTC, gn36 commented
Zurück zu den Versionsinfos: Ich schlage vor, wir werfen das überall raus (auch in der Readme) und schreiben das lediglich bei den Releases automatisiert mit dem build Skript rein, so dass man zumindest bei den erstellten Paketen irgend eine Möglichkeit hat hinterher zu kontrollieren, ob die Version vielleicht veraltet ist. Ob wir das dann in die composer.json oder die Readme schreiben ist mir egal.

2017-01-18 17:30 UTC, Crizz0 commented
Das können wir auch machen, dann wäre das dort auch weg. Würde ich aber jetzt nicht unbedingt in dem PR sehen.

2017-01-18 20:22 UTC, Philipp-K commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Dann sollten wir aber imho auf https://www.phpbb.de/community/viewforum.php?f=144 verweisen

2017-01-18 20:23 UTC, bantu commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Besser ein go-Link?

2017-01-18 21:42 UTC, Crizz0 commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
@bantu Kannst du mir einen go-link für ?f=144 einrichten?

2017-01-20 16:50 UTC, mungo commented on composer.json
> +		"forum": "https://www.phpbb.de/community/"
Ist drin: https://www.phpbb.de/go/lang-support

2017-01-21 12:42 UTC, merged