Prep 3.1.11-RC1 (nur de)
phpbb-de/phpbb-translation pull request #334
Opened 2017-06-30 17:22 UTC by gn36

Bitte genau ansehen, da sind doch einige Dinge dabei die vielleicht doch besser etwas anders formuliert werden sollten, daher auch erst mal nur de, de_x_sie wird dann übernommen, sobald de steht.

Daher wird travis wohl aufgrund fehlender Übersetzungen auch erst mal meckern ;)

Siehe #332

2017-06-30 22:17 UTC, Crizz0 commented on language/de/acp/board.php
> +	'JAB_ALLOW_SELF_SIGNED'			=> 'Erlaube selbst signierte SSL Zertifikate',
Da haben wir immer "erlauben" ans Ende gestellt. "Selbst signierte Zertifikate erlauben"

2017-07-01 08:02 UTC, Philipp-K requested changes
Danke für die Übersetzung. Sind vor allem einige Bindestriche und ein paar Kleinigkeiten

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'ACP_COOKIE_SETTINGS_EXPLAIN'		=> 'Hier legst du die Einstellungen fest, die verwendet werden, um Cookies an die Browser deiner Benutzer zu senden. In den meisten Fällen sollten die Standardwerte au
Ich würde "nicht angemeldet" statt "nicht eingeloggt" verwenden und wie in den anderen Fällen auch zusätzlich auf einen deutschen Artikel verlinken,

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast o
Das Komma vor dem oder muss meiner Ansicht nach weg. Wir haben wohl statt example.com (gültige Domain) immer was anderes mit .tld verwendet - würde ich hier auch machen (bitte mal suchen - ich hab grad keine zur Hand).
"Nun füge einen Punkt vor den gemeinsamen Domain-Namen und füge diesen in das Feld ein." -> "Nun füge einen Punkt gefolgt von dem gemeinsamen Domain-Namen in dieses Feld ein"

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'COOKIE_NAME_EXPLAIN'		=> 'Dies kann ein beliebiger Wert sein, z.B. eine zufällige Buchstabenkombination. Wenn die übrigen Cookie Einstellungen geändert werden sollte der Cookie-Name ebenfalls geänd
Bitte ein Leerzeichen (oder ein &nbsp;) zwischen z. und B., ein Bindestrich zwischen "Cookie" und "Einstellungen" und ein Komma nach "werden"

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'COOKIE_PATH_EXPLAIN'		=> 'Beachte, dass dies immer ein Slash (/) ist, egal wie deine Board-URL aussieht.',
Ist zwar korrekt übersetzt - aber irgendwie etwas merkwürdig (bitte hier immer das gleiche eintragen - wieso erfassen wir es dann?)

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Erlaube selbst signierte SSL Zertifikate',
selbstsignierte SSL-Zertifikate

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED_EXPLAIN'=> 'Erlaube Verbindungen zu einem SMTP Server mit einem selbst signierten SSL Zertifikat. <em><strong>Warnung:</strong> Das Erlauben von selbst signierten SSL Zertifi
SMTP-Server
selbstsigniertes SSL-Zertifikat (2 mal)

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER'				=> 'Verifiziere SSL Zertifikat',
SSL-Zertifikat

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_EXPLAIN'		=> 'Erfordere eine Verifizierung des SSL Zertifikats, das vom SMTP Server verwendet wird. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SSL
SSL-Zertifikat (2 mal)
SMTP-Server

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME'			=> 'Verifiziere SMTP Server Namen',
Verifizierte Name des SMTS-Servers

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erfordere eine Verifizierung des Server Namens für SMTP Server, die SSL / TLS Verbindungen verwenden. <em><strong>Warnung:</strong> Verbindung zu unverifizierten
des Names des SMTP-Servers (evtl. der URL des...)

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_EXPLAIN'		=> 'Erfordere eine Verifizierung des SSL Zertifikats, das vom SMTP Server verwendet wird. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SSL
Das "Erfordere" (auch an anderen Stellen) gefällt mir irgendwie nicht so wirklich. Evtl. auch nur kurz "Verifiziert das SSL-Zertifikat..."

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_ALLOW_SELF_SIGNED'			=> 'Erlaube selbst signierte SSL Zertifikate',
selbstsignierte SSL-Zertifikate

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erfordere die Verifizierung des Server-Namens für Jabber Server, die SSL / TLS Verbindungen verwenden. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit
Der Block muss auch an einigen Stellen analog zum Mail-Server angepasst werden. Danach würde ich ihn mir noch mal im Detail anschauen

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/common.php
> +	'PHP_VERSION_OLD'	=> 'Die PHP-Version auf diesem Server (%1$s) wird von künftigen phpBB-Versionen nicht mehr unterstützt. Die mindestens erforderliche Version ist PHP %2$s. %3$sWeitere Informationen
Evtl. besser "Es wird mindestens PHP x erforderlich sein

2017-07-01 08:02 UTC, Philipp-K commented on language/de/acp/styles.php
> +	'STYLE_VERSION'				=> 'Style Version',
Style-Version

2017-07-01 08:02 UTC, Philipp-K commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_HASH_BCRYPT'		=> 'Aktualisiert veraltete Passwort Hashes und hasht diese mit bcrypt.',
Irgendwie bin ich damit nicht ganz glücklich (wir hashen ja keine Hashes
Aktualisiert veraltete Passwort-Hashes auf bcrypt.
Aktualisiert veraltete Passwort-Hashes, so dass diese bcrypt verwenden.
Verwendet bcrypt zur Aktualisierung veralteter Passwort-Hashes
Aktualisert Passwort-Hashes, die bislang kein bcrypt verwenden

2017-07-01 08:02 UTC, Philipp-K commented on language/de/cli.php
> +	'CLI_FIXUP_UPDATE_HASH_BCRYPT_SUCCESS'		=> 'Die veralteten Passwort Hashes wurden erfolgreich auf bcrypt aktualisiert.',
Passwort-Hashes

2017-07-01 08:02 UTC, Philipp-K commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release  <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu
Ein neues Feature-Release <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release-Ankündigung</strong></a>, um mehr über die Neuerungen zu erfahren und eine Anleitung zum Upgrade zu erhalten.

2017-07-01 08:02 UTC, Philipp-K commented on language/de/ucp.php
> +	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maximale Größe; Breite: %1$s, Höhe: %2$s.',
Doppelpunkt statt Strichpunkt nach Größe

2017-07-01 10:21 UTC, Joyce-Luna commented on language/de/acp/board.php
> +	'ACP_COOKIE_SETTINGS_EXPLAIN'		=> 'Hier legst du die Einstellungen fest, die verwendet werden, um Cookies an die Browser deiner Benutzer zu senden. In den meisten Fällen sollten die Standardwerte au
Ich würde mal die Links dazu testen. Der Link https://www.phpbb.com/support/go/cookie-settings führt zu eine 404 Seite.
Wenn ich richtig geschaut habe, liegt das ganze jetzt hier https://www.phpbb.com/support/docs/en/3.1/kb/article/fixing-incorrect-cookie-settings/

2017-07-01 11:41 UTC, gn36 commented on language/de/acp/board.php
> +	'ACP_COOKIE_SETTINGS_EXPLAIN'		=> 'Hier legst du die Einstellungen fest, die verwendet werden, um Cookies an die Browser deiner Benutzer zu senden. In den meisten Fällen sollten die Standardwerte au
Ich denke das wird noch verlinkt, genau wie bei uns sind auf phpbb.com die go Links nur Weiterleitungen, die sich dann dynamisch anpassen lassen ohne dass bei Änderungen auf .com die Sprachdateien angepasst werden müssen.

2017-07-02 15:41 UTC, gn36 commented on language/de/acp/board.php
> +	'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast o
Gefunden habe ich gerade ein Beispiel mit phpbb.de und ein weiteres mit domain.tld. Ganz einheitlich sind wir offenbar da aktuell nicht. 
Ich würde bei example.com bleiben, denn example.com ist ganz offiziell von der IANA für Beispiele reserviert und kann von niemandem für was anderes registriert werden. Finde ich eigentlich daher für Beispiele gar nicht so schlecht. Die anderen Stellen können wir ja anpassen.

2017-07-02 15:45 UTC, gn36 commented on language/de/acp/board.php
> +	'COOKIE_PATH_EXPLAIN'		=> 'Beachte, dass dies immer ein Slash (/) ist, egal wie deine Board-URL aussieht.',
Das habe ich mich auch gefragt - hier sollten wir vielleicht den Originaltext mal als Bug melden? 

Das macht so in meinen Augen keinen Sinn. In meinen Augen gehört da was hin, das erklärt, dass man den Cookie auf bestimmte Unterordner beschränken kann, wenn man ihn nur im Forum-Ordner sehen will, ansonsten aber auch per / einfach ein domainweit gültiger Cookie gesetzt werden kann.

2017-07-02 15:48 UTC, gn36 commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_EXPLAIN'		=> 'Erfordere eine Verifizierung des SSL Zertifikats, das vom SMTP Server verwendet wird. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SSL
Ok, bessere Idee: "Erzwinge"?

2017-07-02 16:00 UTC, gn36 commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erfordere eine Verifizierung des Server Namens für SMTP Server, die SSL / TLS Verbindungen verwenden. <em><strong>Warnung:</strong> Verbindung zu unverifizierten
Das ist irgendwie insgesamt unrund, oder?

Neuer Vorschlag:
> Erzwinge die Verifikation des Namens des SMTP-Servers, falls die Verbindung per SSL / TLS hergestellt wird.
<em><strong>Warnung:</strong> Eine Verbindung ... </em>

2017-07-02 16:00 UTC, gn36 commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_HASH_BCRYPT'		=> 'Aktualisiert veraltete Passwort Hashes und hasht diese mit bcrypt.',
Ehrlich gesagt wäre ich mir gar nicht so sicher, ob wir nicht durchaus veraltete Hashes zusätzlich mit bcrypt hashen, schließlich knackt das Board nicht alle alten Hashes und verschlüsselt diese dann neu, wenn ich den Konsolebefehl ausführe, um die Passwörter neu zu verschlüsseln müsste man die aber erst mal haben.

2017-07-14 16:43 UTC, Crizz0 commented
@gn36 Bist du noch dran?

2017-07-14 22:29 UTC, gn36 commented
Ich habe die eindeutigen Dinge lokal eingepflegt,  aber bei einem paar Dingen warte ich auf eure Rückmeldung.

2017-07-15 09:44 UTC, Crizz0 commented on language/de/acp/board.php
> +	'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast o
Ja, nimm  example.org oder .com.

Müssen wir dann mal in einem PR angleichen.

2017-07-15 09:45 UTC, Crizz0 commented on language/de/acp/board.php
> +	'ACP_COOKIE_SETTINGS_EXPLAIN'		=> 'Hier legst du die Einstellungen fest, die verwendet werden, um Cookies an die Browser deiner Benutzer zu senden. In den meisten Fällen sollten die Standardwerte au
Habe ich bei .com gemeldet. Ergo können wir dann gerne noch unseren deutschen Go-Link einbauen, sofern wir dafür Content haben.

2017-07-15 09:47 UTC, Crizz0 commented on language/de/acp/board.php
> +	'COOKIE_PATH_EXPLAIN'		=> 'Beachte, dass dies immer ein Slash (/) ist, egal wie deine Board-URL aussieht.',
Ich erstelle mal ein Ticket.

2017-07-15 10:06 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_EXPLAIN'		=> 'Erfordere eine Verifizierung des SSL Zertifikats, das vom SMTP Server verwendet wird. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SSL
Wir wärs mit "verlangen"? 

`Verlange eine Verifizierung des SSL-Zertifikats, das vom SMTP-Server verwendet wird. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SSL-Zertifikaten kann die Sicherheit beeinträchtigen.</em>',`

2017-07-15 10:06 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erfordere eine Verifizierung des Server Namens für SMTP Server, die SSL / TLS Verbindungen verwenden. <em><strong>Warnung:</strong> Verbindung zu unverifizierten
Finde ich besser.

2017-07-15 10:08 UTC, Crizz0 commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_HASH_BCRYPT'		=> 'Aktualisiert veraltete Passwort Hashes und hasht diese mit bcrypt.',
Ich hab mal Marc gefragt, er hat gesagt, dass diese neue Funktion die alten Hashes nochmal mit Bcrypt hashet (doppelt) und beim nächsten Login dann nur noch alleine mit bcrypt. So liegen die Hashes nur noch in Bcrypt vor und müssen nicht geknackt werden und man muss nicht warten, bis die User sich mal wieder anmelden, was viele eben nicht tun.

2017-07-16 13:10 UTC, Crizz0 commented
Habe dir die Rückmeldungen gegeben.

2017-07-16 21:39 UTC, gn36 commented
So. Ich hoffe ich habe alles, de_x_sie ist nun auch dabei.

2017-07-17 15:24 UTC, Crizz0 requested changes
Abgesehen davon sieht das mMn jetzt ganz gut aus.

2017-07-17 15:24 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Selbst signierte SSL-Zertifikate erlauben',
sind wir sicher, dass es "selbst signierte" und nicht "selbstsignierte" heißt?

2017-07-17 15:24 UTC, Crizz0 commented on language/de/cli.php
> +	'CLI_DESCRIPTION_UPDATE_HASH_BCRYPT'		=> 'Hasht veraltete Passwort-Hashes mit bcrypt und aktualisiert diese beim nächsten Login.',
Die CLI Funktion macht eigentlich nur ersteres, sie hashed die alten Hashes erneut, so dass alles in bcrypt vorliegt.

Der Login sorgt für den bcrypt hash ohne Zwischenschritt, das macht aber die CLI hier nicht. Daher ist der zweite Satzteil mMn hier unangebracht.

2017-07-17 15:24 UTC, Crizz0 commented on language/de/cli.php
> +	'CLI_FIXUP_UPDATE_HASH_BCRYPT_SUCCESS'		=> 'Die veralteten Passwort-Hashes wurden erfolgreich auf bcrypt aktualisiert.',
Das ist das Ergebnis von 71, hier würde ich es genauso so lassen und oben anpassen.

2017-07-17 15:24 UTC, Crizz0 commented on language/de_x_sie/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release  <strong>%1$s</strong> ist verfügbar. Bitte lesen Sie <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerunge
Ein Leerzeichen vor <strong> zu viel.

2017-07-17 15:24 UTC, Crizz0 commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release  <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu
Ein Leerzeichen vor <strong> ist zu viel.

2017-07-17 15:44 UTC, Crizz0 requested changes

2017-07-17 15:44 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Selbst signierte SSL-Zertifikate erlauben',
Das sollte afaik "Selbstsignierte" heißen, also zusammen.

2017-07-17 20:46 UTC, gn36 commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Selbst signierte SSL-Zertifikate erlauben',
Ich würde das nicht zusammen schreiben.

2017-07-17 20:47 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Selbst signierte SSL-Zertifikate erlauben',
Ich hab mit @Elsensee und noch 2 anderen geredet, ich denke das gehört zusammen.

2017-07-17 20:58 UTC, Crizz0 approved these changes

2017-07-17 20:59 UTC, gn36 commented
na gut. Völlig überzeugt bin ich aber nicht.

2017-07-17 21:22 UTC, DrDeath commented on language/de/acp/board.php
> +	'SMTP_ALLOW_SELF_SIGNED'		=> 'Selbst signierte SSL-Zertifikate erlauben',
https://dict.leo.org/englisch-deutsch/self%20signed
Adjektive.... alle "self-xxxx" Übersetzungen werden zusammen geschrieben.....

2017-07-18 09:49 UTC, Philipp-K requested changes
Sie noch nicht geprüft

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast o
alt: entferne die Subdomains bis du den gemeinsamen Domainteil gefunden hast, in diesem Beispiel <i>example.com</i>.
neu: entferne die Subdomains, bis du den gemeinsamen Domainteil gefunden hast; in diesem Beispiel <i>example.com</i>.
Evtl. auch "Anteil der Domain"

alt: Nun füge einen Punkt vor den gemeinsamen Domain-Namen und füge diesen in das Feld ein.
neu: Nun füge einen Punkt vor den gemeinsamen Domain-Namen und trage diesen in das Feld ein.

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'COOKIE_NAME_EXPLAIN'		=> 'Dies kann ein beliebiger Wert sein, z.&nbsp;B. eine zufällige Buchstabenkombination. Wenn die übrigen Cookie Einstellungen geändert werden sollte der Cookie-Name ebenfalls
Komma nach "werden"

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erzwinge eine Verifizierung des Namens des SMTP-Servers, falls eine SSL / TLS Verbindung verwendet wird. <em><strong>Warnung:</strong> Verbindung zu unverifiziert
Analog zu den anderen Beispielen: Warnung: **Die** Verbindung

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_ALLOW_SELF_SIGNED_EXPLAIN' => 'Erlaube Verbindungen zu Jabber Servern mit selbstsigniertem SSL-Zertifikat. <em><strong>Warnung:</strong></em> Das Erlauben von selbstsignierten SSL-Zertifikaten
Jabber-Servern

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_GTALK_NOTE'				=> 'Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht gefunden werden konnte. Diese Funktion ist in PHP 4 nicht verfügbar und nicht
nicht gefunden -> nicht verfügbar

Am Rande: laut PHP funktioniert die Funktion unter Windows seit PHP 5.3 (http://php.net/manual/de/function.dns-get-record.php)

2017-07-18 09:49 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_VERIFY_PEER_EXPLAIN'		=> 'Erzwinge die Verifizierung von SSL-Zertifikaten, die vom Jabber Server verwendet werden. <em><strong>Warnung:</strong> Die Verbindung zu Servern mit unverifizierten SS
Jabber-Server

2017-07-18 09:49 UTC, Philipp-K commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu e
Feature-Release
Release-Ankündigung (oder hatten wir nicht immer -Bekanntmachung verwendet?)

2017-07-18 16:43 UTC, gn36 commented on language/de/acp/board.php
> +	'JAB_GTALK_NOTE'				=> 'Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht gefunden werden konnte. Diese Funktion ist in PHP 4 nicht verfügbar und nicht
Das wurde inhaltlich nicht geändert, nur die Leerzeichen wurden verändert. Können wir natürlich trotzdem ändern, allerdings finde ich das doppelte "verfügbar" nicht ganz optimal.

2017-07-19 03:24 UTC, gn36 commented
Vor Samstag wird das bei mir fürchte ich nichts mehr...

2017-07-19 18:49 UTC, Crizz0 commented on language/de/acp/board.php
> +	'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast o
Ergebnis:

> 'COOKIE_DOMAIN_EXPLAIN'		=> 'In den meisten Fällen ist die Cookie-Domain optional. Lasse diese leer, wenn du dir unsicher bist.<br /><br /> Falls du dein Board mit anderer Software integriert hast oder mehrere Domains verwendest, dann kannst du die benötigte Cookie-Domain wie folgt bestimmen: Falls du Domainkombinationen wie <i>example.com</i> und <i>forums.example.com</i> oder auch <i>forums.example.com</i> und <i>blog.example.com</i> verwendest, dann entferne die Subdomains, bis du den gemeinsamen Domainteil gefunden hast; in diesem Beispiel <i>example.com</i>. Nun füge einen Punkt vor den gemeinsamen Domain-Namen und trage diesen in das Feld ein. In unserem Beispiel würdest du also <i>.example.com</i> einfügen (beachte den Punkt am Anfang).',

Okay?

2017-07-19 18:50 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_VERIFY_PEER_NAME_EXPLAIN'	=> 'Erzwinge eine Verifizierung des Namens des SMTP-Servers, falls eine SSL / TLS Verbindung verwendet wird. <em><strong>Warnung:</strong> Verbindung zu unverifiziert
Ergebnis:

> <em><strong>Warnung:</strong> Die Verbindung zu unverifizierten Servern kann die Sicherheit beeinträchtigen.</em>',

2017-07-19 18:52 UTC, Crizz0 commented on language/de/acp/board.php
> +	'JAB_GTALK_NOTE'				=> 'Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht gefunden werden konnte. Diese Funktion ist in PHP 4 nicht verfügbar und nicht
Um die Dopplung zu vermeiden "nicht vorhanden ist"?
Ergebnis:

> Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht verfügbar ist. Diese Funktion ist in PHP 4 nicht vorhanden und nicht in Windows-Plattformen implementiert. Sie funktioniert im Moment nicht auf BSD-basierten Systemen inklusive Mac OS.',

2017-07-19 18:57 UTC, Crizz0 commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu e
language\de\install.php:
`'VERSION_NOT_UP_TO_DATE_ACP' => ... Release-Ankündigung ...`
language\de\acp\extensions.php:
`	'ANNOUNCEMENT_TOPIC' => 'Release-Bekanntmachung', `

Würde ich dann einfach angleichen wollen, sind ja nur drei stellen.

2017-07-20 08:18 UTC, Philipp-K commented on language/de/acp/board.php
> +	'JAB_GTALK_NOTE'				=> 'Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht gefunden werden konnte. Diese Funktion ist in PHP 4 nicht verfügbar und nicht
Passt so für mich

2017-07-20 08:29 UTC, Philipp-K commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu e
Wir haben bislang immer Bekanntmachung (evtl. auch Release-Bekanntmachung) verwendet

2017-07-20 08:51 UTC, Crizz0 commented on language/de/install.php
> +	'UPGRADE_INSTRUCTIONS'			=> 'Ein neues Feature Release <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Release Ankündigung</strong></a> um die Neuerungen zu e
Dann machen wir hier auch "Release-Bekanntmachung".

2017-07-21 06:03 UTC, gn36 commented on language/de/acp/board.php
> +	'JAB_GTALK_NOTE'				=> 'Beachte, dass GTalk nicht funktionieren wird, da die <samp>dns_get_record</samp>-Funktion nicht gefunden werden konnte. Diese Funktion ist in PHP 4 nicht verfügbar und nicht
Dito

2017-07-21 18:35 UTC, merged