Adds new language key ACP_VIGLINK_SUPPORT_EXPLAIN
phpbb-de/phpbb-translation pull request #337
Opened 2017-07-17 16:25 UTC by Crizz0

Teile von #333 (nur Viglink)

2017-07-17 21:10 UTC, gn36 approved these changes

2017-07-18 09:52 UTC, Philipp-K requested changes

2017-07-18 09:52 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SUPPORT_EXPLAIN'	=> 'Du wirst nicht länger auf diese Seite weitergeleitet, sobald du unten auf dieser Seite deine gewünschten Einstellungen ausgewählt und auf "Absenden" geklickt hast.'
Einstellungen durchgeführt?

2017-07-18 10:13 UTC, Crizz0 commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SUPPORT_EXPLAIN'	=> 'Du wirst nicht länger auf diese Seite weitergeleitet, sobald du unten auf dieser Seite deine gewünschten Einstellungen ausgewählt und auf "Absenden" geklickt hast.'
Also "Änderungen" kann man durchführen. Aber Einstellungen? 

"Vornehmen" könnte ich mir noch vorstellen.

2017-07-18 13:11 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SUPPORT_EXPLAIN'	=> 'Du wirst nicht länger auf diese Seite weitergeleitet, sobald du unten auf dieser Seite deine gewünschten Einstellungen ausgewählt und auf "Absenden" geklickt hast.'
Dann vornehmen

2017-07-19 07:41 UTC, gn36 approved these changes

2017-07-20 08:16 UTC, Philipp-K requested changes

2017-07-20 08:16 UTC, Philipp-K commented on ext/phpbb/viglink/language/de/viglink_module_acp.php
> +	'ACP_VIGLINK_SUPPORT_EXPLAIN'	=> 'Du wirst nicht länger auf diese Seite weitergeleitet, sobald du unten auf dieser Seite deine gewünschten Einstellungen vorgenommen und auf "Absenden" geklickt hast.
Sorry, fällt mir jetzt erst auf: bitte die korrekten Anführungszeichen (wie bei ACP_VIGLINK_SETTINGS_CHANGE) verwenden

2017-07-23 08:07 UTC, Philipp-K approved these changes

2017-07-23 12:23 UTC, merged