Anpassungen 3.1.11-RC1 -> 3.1.11
phpbb-de/phpbb-translation pull request #338
Opened 2017-07-17 21:30 UTC by gn36

Versionsinfo.

Fixes #336

2017-07-18 09:51 UTC, Philipp-K requested changes

2017-07-18 09:51 UTC, Philipp-K commented on language/de/acp/common.php
> +	'VERSIONCHECK_INVALID_ENTRY'	=> 'Die neueste Versionsinformation enthält einen nicht unterstützten Eintrag.',
Ich würde hier immer "Die Information über die aktuelle Version" (wie bei VERSIONCHECK_FAIL) verwenden

2017-07-19 07:42 UTC, gn36 commented on language/de/acp/common.php
> +	'VERSIONCHECK_INVALID_ENTRY'	=> 'Die neueste Versionsinformation enthält einen nicht unterstützten Eintrag.',
Ok, macht Sinn.

2017-07-21 19:33 UTC, Crizz0 commented
@Philipp-K Neben der Änderung in jeweils:

> Die Information über die aktuelle Version enthält einen nicht unterstützten Eintrag.

Wäre der PR sonst i.O.?

2017-07-22 20:37 UTC, closed without merging