Änderungen für 3.2.3-RC2
phpbb-de/phpbb-translation pull request #361
Opened 2018-08-10 19:53 UTC by Crizz0

Nach Punkt 2 von #355

2018-08-11 09:59 UTC, gn36 commented
Irgendwas scheint schief zu sein mit PHP 7.1. Inhaltlich sieht's für mich ok aus.

2018-08-11 09:59 UTC, gn36 approved these changes

2018-08-11 11:20 UTC, Crizz0 commented
@gn36 Irgendeine Idee zum Travis Fehler?

2018-08-12 07:17 UTC, gn36 commented
Ehrlich gesagt nicht. Das geht ja schon schief bei der Installation von php. Das hat ja noch nichts mit unserem Skript zu tun.

Entweder wir warten ein wenig und triggern den Build noch mal oder wir ignorieren den Fehler einfach.

2018-08-13 20:15 UTC, Philipp-K requested changes

2018-08-13 20:15 UTC, Philipp-K commented on language/de/acp/search.php
> +		2	=> 'Alle Beiträge bis zur Beitrags-ID #%2$d wurden bereits vom Suchindex entfernt, davon %1$d Beiträge in diesem Durchlauf.<br />',
Wenn ich das so durchlese: "Die Beiträge" statt "Alle Beiträge" finde ich hier passender

2018-08-13 20:15 UTC, Philipp-K commented on language/de/acp/search.php
> +		2	=> 'Die aktuelle Löschrate beträgt näherungsweise %1$.1f Beiträge pro Sekunde.<br />Index wird gelöscht…',
näherungsweise -> ungefähr

2018-08-13 20:15 UTC, Philipp-K commented on language/de/help/faq.php
> +	'HELP_FAQ_LOGIN_DELETE_COOKIES_ANSWER'	=> '„Alle Cookies löschen“ löscht die Cookies, die phpBB erstellt hat und die dafür sorgen, dass du im Forum angemeldet bleibst. Außerdem ermöglichen Cookies e
Ich würde dann "des Boards" auch am Ende entfernen

2018-08-13 20:15 UTC, Philipp-K commented on language/de/help/faq.php
> +	'HELP_FAQ_LOGIN_DELETE_COOKIES_QUESTION'	=> 'Wozu ist die „Alle Cookies löschen“-Funktion?',
Wozu ist die Funktion "..." fände ich besser

2018-08-15 18:33 UTC, Crizz0 commented on language/de/acp/search.php
> +		2	=> 'Alle Beiträge bis zur Beitrags-ID #%2$d wurden bereits vom Suchindex entfernt, davon %1$d Beiträge in diesem Durchlauf.<br />',
Ich weiß nicht, das klingt irgendwie nicht wirklich besser. Müsste dann auch "SEARCH_INDEX_CREATE_REDIRECT" betreffen.

2018-08-16 22:28 UTC, gn36 commented on language/de/acp/search.php
> +		2	=> 'Alle Beiträge bis zur Beitrags-ID #%2$d wurden bereits vom Suchindex entfernt, davon %1$d Beiträge in diesem Durchlauf.<br />',
Es geht finde ich beides, alle finde ich aber besser.

2018-09-12 18:16 UTC, gn36 reviewed
Soweit ich das sehe sind alle Änderungswünsche von PhilippK drin.

2018-09-13 10:49 UTC, Crizz0 commented
@Philipp-K Hast du noch Änderungswünsche?

2018-09-13 20:37 UTC, Philipp-K approved these changes
Aus meiner Sicht OK

2018-09-14 11:03 UTC, merged