BOARD_DATE_FORMAT_EXPLAIN
phpbb-de/phpbb-translation pull request #366
Opened 2018-09-23 15:02 UTC by LukeWCS

Richtig bei de, falsch bei de_x_sie.

2018-09-23 16:42 UTC, Crizz0 commented
Hi,

bitte mal die beiden unnötigen Commit rauswerfen und die commit message aussagekräftiger gestalten. 

Grüße

2018-09-23 16:43 UTC, Crizz0 requested changes
Commit message

2018-09-23 17:19 UTC, LukeWCS commented
Nachricht geändert, wobei ich nicht weiss was ihr hier erwartet. Es wäre hilfreich wenn man dafür irgendwo Richtlinien nachlesen könnte.

Dann weiss ich nicht wie ich diese commits entfernen kann, die haben mich bei meiner Arbeit mit GH noch nie gestört.

2018-09-23 20:18 UTC, Crizz0 commented
Die Commit-Message kannst du mit "git commit --amend" anpassen und dann "git push -f ..." (force push). Dort steht aktuell nur noch: 
> Update ucp.php 

Und nicht, was geändert wird und warum.

Die anderen beiden Merge-Commits sind vielleicht da, weil du dein lokales Repo nicht richtig aktualisiert hast. Ergo bitte rebase auf dem richtigen branch in der aktuellen Version.

2018-09-23 20:35 UTC, LukeWCS commented
Ich arbeite mit GH Desktop, nicht mit der Shell. Ich habe davon aktuell noch keine Ahnung. Dann lösch das hier bitte einfach.

2018-09-23 20:35 UTC, closed without merging

2018-09-23 20:41 UTC, Crizz0 commented
Die Funktionen gibt es dort vmtl. auch, sind wohl einfach nur ein paar Button.

2018-09-23 21:13 UTC, LukeWCS commented
Nein Chris, leider nicht. GH Desktop ist relativ einfach gehalten, bietet aber alles was ich brauche. Vor allem die Funktion einen ganzen Ordner samt Unterordner und Dateien in einem Rutsch und als 1 Commit an GH Web zu übertragen. Vor Jahren musste ich das einzeln im GH Web machen, du erinnerst dich vielleicht, als ich das ziemlich grosse Änderungspaket hier eingereicht habe mit zig einzelnen Commits weil ich es einfach nicht anders machen konnte? Das ist jetzt Geschichte. Aber für die Shell hab ich einfach keinen Nerv mich da auch noch einzuarbeiten. Der Tag hat nur 24 Stunden. ^^

2018-09-24 17:18 UTC, Crizz0 commented
Dachte da nimmst du einfach den Button dort rechts z.B. 
![git-gui-commit-amend](https://user-images.githubusercontent.com/1311778/45967516-8cea6400-c02e-11e8-904e-494a75f04496.PNG)

2018-09-24 18:38 UTC, LukeWCS commented
Das ist jedoch Git Gui, nicht GH Desktop, dort gibt es das nicht. Ich verwenden seit kurzem in geringem Umfang auch Git Gui und gitk in Kombination um bestimmte Dinge zu erreichen, die in GH Web gar nicht gehen. Zum Beispiel ein Repository nach zig Versuchen wieder auf einen ordentlichen Stand zurückzusetzen und anschliessend per erzwungenem Push auch das Online Repository zu ersetzen. Die Handhabung dafür ist aber auch schon reichlich umständlich in meinen Augen. Ich teste deshalb seit heute eine von zwei GUI's die offenbar die Git Shell komplett ersetzen können. Dementsprechend komplex sind sie auch und braucht Einarbeitungszeit. Dafür hat man eine GUI in der man alles machen kann und nicht zwei, wie Git Gui und gitk.

Was "Amend Last Commit" angeht, damit würde ich aber einen Commit rückgängig machen soweit ich das verstanden habe? Damit würde ich aber auch die Basis für meine Änderung entziehen, oder nicht? Die Möglichkeit einfach einen Commit zu löschen wie du schreibst, habe ich nicht gefunden im Netz. Alles schreiben nur von rückgängig machen, was ich ja aber nicht will. Ich verstehe nicht ganz was das Problem mit den beiden Commits ist Crizzo, die enthalten keinerlei Änderungen die euer Repository stören würden, warum ist das ein Problem?

2018-09-24 20:44 UTC, Crizz0 commented
Primär sind die beiden "commits" einfach völlig unnötig und blähen die Historie unnötig auf. Deutet eben darauf hin, dass du nicht korrekt auf dem letzten "origin/3.2.x" branch aufgebaut hast. Ergo hat wohl ein "git fetch orgin" --> "git pull origin 3.2.x" gefehlt, was deinen lokalen branch aktuell hält.

Den Commit löschen kannst du mit "git rebase ...", "git commit --amend" hängt eben zusätzliche Änderungen an den gleiche Commit an, wenn du nix änderst, kannst du so einfach die Commit-Message des letzten Commits ändern, weil du nochmal das Dialog-Fenster öffnest.

Kurz um, lad mal das Repo frisch runter, erstell einen neuen branch auf "3.2.x" und reiche den Typo erneut ein, dann ist wirklich nur der eine Commit drin und es wird "gemerged".

Grüße

2018-09-25 09:46 UTC, LukeWCS commented
Moin

> Primär sind die beiden "commits" einfach völlig unnötig und blähen die Historie unnötig auf. Deutet eben darauf hin, dass du nicht korrekt auf dem letzten "origin/3.2.x" branch aufgebaut hast.

Korrekt auf eurem 3.2 Branch aufgebaut war der PR schon, denn sonst hätte GH nicht gemeldet, das der PR problemlos migriert werden kann. Zudem würde man sofort sehen, wenn es sonstige Abweichungen zu eurem Branch geben würde. Das Problem hier ist/war eher, wie ich meinen Fork aktualisiert habe. Bis heute hatte ich schlicht keine andere Möglichkeit und bin nach dieser Anleitung vorgegangen:

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

Ich habe also die ganz normalen Funktionen von GH Web dazu benutzt. Das war vielleicht anders als du es machst, aber deswegen nicht falsch. Wäre es falsch, würde diese Funktion im GH Web auf diese Weise wohl auch nicht benutzt werden können. Zudem gibt es diese Anleitung in verschiedenen Varianten im Netz zu finden. Das heisst bei denjenigen die nur GH Web nutzen, ist dieser Weg Usus. Das Bild ergab sich mir jedenfalls, beim stöbern nach Antworten.

Du kannst nicht davon ausgehen, das jeder der die Funktionalität von GH benutzen will, ebenso die Shell verwenden will. Ebenso kannst du nicht erwarten, das alle den gleichen Wissensstand wie du haben, was GH angeht.

Aber okay, nun weiss ich warum du die zusätzlichen Commits nicht willst und auch das es andere Wege gibt. Das muss man aber alles erstmal wissen. Ich habe mich mittlerweile soweit in das neue Programm eingearbeitet und auch schon erfolgreich einige meiner Forks aktualisiert, ohne einen PR dazu benutzen zu müssen. Auch weiss ich jetzt, wie ich meine Repositorys auf einen bestimmten Commit-Stand zurücksetzen kann. Das habe ich auch mit meinem Fork von eurem Repo gemacht, damit ich einen sauberen Stand zum aktualisieren hatte, ohne die beiden "problematischen" Commits (PR's) von mir. Ich habe also nicht das Repo neu heruntergeladen bzw. den Fork neu erstellt, sondern bin den "steinigen" Weg gegangen, um zu lernen. Somit kann ich nun meine Forks zukünftig auf direktem Weg aktuell halten und muss nicht mehr online einen PR dazu benutzen. Das Programm scheint auch alles zu bieten, was du hier bisher an Funktionen genannt hast.