Übersetzung für 3.2.4-RC1
phpbb-de/phpbb-translation pull request #369
Opened 2018-10-29 19:34 UTC by Crizz0

for #368

2018-10-30 22:11 UTC, Crizz0 commented
Der schlägt aktuell noch fehl, weil der PR älter als der Validator v1.4.1 ist und Travis sich aktuell weigert 1.4.1 zu laden.

2018-11-01 18:38 UTC, Philipp-K requested changes
Analog dann ggf. bei Sie

2018-11-01 18:38 UTC, Philipp-K commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn keine Angaben gemacht werden, verwendet benutzerdefinierte
Ich würde da näher an der Ursprungsversion bleiben:

```suggestion
	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinierte Profilfeld die Einstellungen für die Standardsprache verwendet. Du kannst diese Angaben auch später ergänzen.',
```

2018-11-01 18:38 UTC, Philipp-K commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_EDIT'			=> 'Da du mehr als ein Sprachpaket installiert hast, kannst du hier die Angaben für die anderen Sprachen ändern oder ergänzen. Wenn keine Angaben gemacht werden, verwendet da
```suggestion
	'STEP_3_EXPLAIN_EDIT'			=> 'Da du mehr als ein Sprachpaket installiert hast, kannst du hier die Angaben für die anderen Sprachen ändern oder ergänzen. Wenn du keine Angaben machst, werden für dieses benutzerdefinierte Profilfeld die Einstellungen für die Standardsprache verwendet.',
```

2018-11-01 18:38 UTC, Philipp-K commented on language/de/captcha_qa.php
> +	'QUESTIONS_EXPLAIN'			=> 'Bei jedem Formular, für das du das Q&amp;A-Plugin aktiviert hast, wird den Benutzern eine der hier festgelegten Fragen gestellt. Um dieses Plugin zu nutzen, muss mindestens
```suggestion
	'QUESTIONS_EXPLAIN'			=> 'Bei jedem Formular, für das du das Q&amp;A-Plugin aktiviert hast, wird den Benutzern eine der hier festgelegten Fragen gestellt. Um dieses Plugin zu nutzen, muss mindestens eine Frage in der Standardsprache festgelegt werden. Die Fragen sollten von der Zielgruppe des Boards leicht zu beantworten sein, aber sich nicht durch eine automatisierte Suchmaschinenanfrage beantworten lassen. Eine geeignete Frage reicht aus. Sobald sich Spam-Registrierungen häufen, sollte die Frage ausgewechselt werden. Aktiviere die strenge Prüfung, wenn die Antworten von der Groß- und Kleinschreibung, der Zeichensetzung oder von Leerzeichen abhängig sind.',
```

2018-11-01 18:38 UTC, Philipp-K commented on language/de/email/newtopic_notify.txt
> +
Wir haben die Leerzeile bislang immer weggelassen - würde ich daher auch hier machen

2018-11-01 18:38 UTC, Philipp-K commented on language/de/ucp.php
> +	'EMAIL_NOT_UNIQUE'			=> 'Die angebene E-Mail-Adresse wird von mehreren Benutzern verwendet. Du musst zusätzlich den Benutzernamen angeben.',
```suggestion
	'EMAIL_NOT_UNIQUE'			=> 'Die angegebene E-Mail-Adresse ist mehreren Benutzern zugeordnet. Du musst zusätzlich den Benutzernamen angeben.',
```

Ist zwar nicht wörtlich - aber imho korrekter :-)

2018-11-01 18:38 UTC, Philipp-K commented on language/de/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Sofern dein Account existiert, wurde ein neues Passort zu deiner hinterlegten E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass du
Auch etwas freier:
```suggestion
	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du gesperrt wurdest, dein Account nicht aktiviert ist oder du nicht berechtigt bist, dein Passwort zu ändern. Kontaktiere die Board-Administration, falls eine der Gründe zutreffen sollte. Überprüfe zudem deinen Spamfilter.',
```

2018-11-01 18:38 UTC, Philipp-K commented on language/de/viewtopic.php
> +	'NO_AUTH_PRINT_TOPIC'	=> 'Du bist nicht berechtigt Themen auszudrucken.',
```suggestion
	'NO_AUTH_PRINT_TOPIC'	=> 'Du bist nicht berechtigt, Themen auszudrucken.',
```

2018-11-10 20:50 UTC, Philipp-K requested changes
Noch ein paar Kleinigkeiten

2018-11-10 20:50 UTC, Philipp-K commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinier
"die Einstellungen für die Standardsprache" oder "die Einstellungen der Standardsprache"?

2018-11-10 20:50 UTC, Philipp-K commented on language/de/common.php
> -	'ACCOUNT_NOT_ACTIVATED'			=> 'Dein Benutzerkonto ist noch nicht aktiviert worden.',
Evtl. auch "Dein Benutzerkonto wurde noch nicht aktiviert"

2018-11-10 20:50 UTC, Philipp-K commented on language/de/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du
```suggestion
	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du gesperrt wurdest, dein Account nicht aktiviert ist oder du nicht berechtigt bist, dein Passwort zu ändern. Kontaktiere die Board-Administration, falls einer der Gründe zutreffen sollte. Überprüfe zudem deinen Spamfilter.',
```

2018-11-10 21:03 UTC, Crizz0 commented on language/de/common.php
> -	'ACCOUNT_NOT_ACTIVATED'			=> 'Dein Benutzerkonto ist noch nicht aktiviert worden.',
Der Satz wurde gelöscht, da macht eine Korrektur keinen Sinn mehr.

2018-11-11 09:22 UTC, gn36 requested changes
Mehr als die Änderung von Philipp habe ich auch nicht gefunden.

2018-11-11 09:22 UTC, gn36 commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinier
in meinen Augen geht beides. Da man nicht die Sprache selbst einstellt sondern es um benutzerdefinierte Profilfelder geht, deren Einstellungen man ändert wäre ich eher für "für die".

2018-11-11 09:22 UTC, gn36 commented on language/de/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du
👍

2018-11-11 09:22 UTC, gn36 commented on language/de_x_sie/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an Ihre hinterlegte E-Mail-Adresse gesendet. Falls Sie keine E-Mail erhalten, kann es daran liegen, dass kein passender Account existiert, S
```suggestion
	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an Ihre hinterlegte E-Mail-Adresse gesendet. Falls Sie keine E-Mail erhalten, kann es daran liegen, dass kein passender Account existiert, Sie gesperrt wurden, Ihr Account nicht aktiviert ist oder Sie nicht berechtigt sind, Ihr Passwort zu ändern. Kontaktieren Sie die Board-Administration, falls einer der Gründe zutreffen sollte. Überprüfen Sie zudem Ihren Spamfilter.',
```

2018-11-11 11:44 UTC, Crizz0 commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinier
Letzteres klingt aber nicht so umständlich.

2018-11-11 18:00 UTC, gn36 requested changes

2018-11-11 18:00 UTC, gn36 commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinier
Dann aber in beiden gleich
```suggestion
	'STEP_3_EXPLAIN_CREATE'			=> 'Da du mehr als ein Sprachpaket installiert hast, musst du auch Angaben für die anderen Sprachen machen. Wenn du keine Angaben machst, werden für dieses benutzerdefinierte Profilfeld die Einstellungen der Standardsprache verwendet. Du kannst diese Angaben auch später ergänzen.',
```

2018-11-11 21:10 UTC, Philipp-K commented on language/de/common.php
> -	'ACCOUNT_NOT_ACTIVATED'			=> 'Dein Benutzerkonto ist noch nicht aktiviert worden.',
Ach komm :-)

2018-11-18 17:10 UTC, gn36 approved these changes

2018-11-18 21:16 UTC, Philipp-K requested changes

2018-11-18 21:16 UTC, Philipp-K commented on language/de/acp/profile.php
> +	'STEP_3_EXPLAIN_EDIT'			=> 'Da du mehr als ein Sprachpaket installiert hast, kannst du hier die Angaben für die anderen Sprachen ändern oder ergänzen. Wenn du keine Angaben machst, werden für dieses
```suggestion
	'STEP_3_EXPLAIN_EDIT'			=> 'Da du mehr als ein Sprachpaket installiert hast, kannst du hier die Angaben für die anderen Sprachen ändern oder ergänzen. Wenn du keine Angaben machst, werden für dieses benutzerdefinierte Profilfeld die Einstellungen der Standardsprache verwendet.',
```

2018-11-18 21:16 UTC, Philipp-K commented on language/de/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du
```suggestion
	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passwort wurde an deine hinterlegte E-Mail-Adresse gesendet. Falls du keine E-Mail erhälst, kann es daran liegen, dass kein passender Account existiert, du gesperrt wurdest, dein Account nicht aktiviert ist oder du nicht berechtigt bist, dein Passwort zu ändern. Kontaktiere die Board-Administration, falls einer der Gründe zutreffen sollte. Überprüfe zudem deinen Spamfilter.',
```

2018-11-18 21:16 UTC, Philipp-K commented on language/de_x_sie/ucp.php
> +	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passort wurde an Ihre hinterlegte E-Mail-Adresse gesendet. Falls Sie keine E-Mail erhalten, kann es daran liegen, dass kein passender Account existiert, S
```suggestion
	'PASSWORD_UPDATED_IF_EXISTED'	=> 'Ein neues Passwort wurde an Ihre hinterlegte E-Mail-Adresse gesendet. Falls Sie keine E-Mail erhalten, kann es daran liegen, dass kein passender Account existiert, Sie gesperrt wurden, Ihr Account nicht aktiviert ist oder Sie nicht berechtigt sind, Ihr Passwort zu ändern. Kontaktieren Sie die Board-Administration, falls einer der Gründe zutreffen sollte. Überprüfen Sie zudem Ihren Spamfilter.',
```

2018-11-19 21:21 UTC, Philipp-K approved these changes

2018-11-19 21:34 UTC, merged