Removes double : in online_users_total
phpbb-de/phpbb-translation pull request #370
Opened 2018-10-30 21:38 UTC by Crizz0

for #362

2018-10-31 12:27 UTC, Elsensee requested changes
Nein. Es ist im Englischen genauso und fungiert als Trenner.

2018-10-31 12:28 UTC, Crizz0 commented
Laut hanakin ist das kein Design Element und kann angepasst werden. 

Am 31. Oktober 2018 13:27:21 MEZ schrieb Oliver Schramm <notifications@github.com>:
>Elsensee requested changes on this pull request.
>
>Nein. Es ist im Englischen genauso und fungiert als Trenner.
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb-de/phpbb-translation/pull/370#pullrequestreview-170224082

2018-10-31 12:41 UTC, Elsensee commented
Klar, aber sieht ein einzelnes Zeichen nicht irgendwie komisch aus?

2018-10-31 14:02 UTC, Crizz0 commented
Naja, jetzt sieht es aus wie ein Tippfehler, danach imo besser.

2018-11-01 18:20 UTC, Philipp-K commented
Ich bin auch für "belassen"

2018-11-01 21:04 UTC, closed without merging