Datenschutzerklärung überarbeitet nach User-Feedback
phpbb-de/phpbb-translation pull request #373
Opened 2018-11-11 12:27 UTC by Crizz0

Muss man noch das eine oder andere ergänzen, aber wir wissen ja, dass zumindest die aktuelle nicht mehr passend ist, nach DSGVO reicht das vmtl. so nicht aus, ist aber durch uns auch nicht zu erstellen.

2018-11-18 17:08 UTC, gn36 requested changes

2018-11-18 17:08 UTC, gn36 commented on language/de/ucp.php
> +		<ol style="list-style-type: decimal;"><li>Die Forensoftware phpBB erstellt bei deinem Besuch des Boards mehrere Cookies. Cookies sind kleine Textdateien, die dein Browser als temporäre Dateien able
```suggestion
		<ol style="list-style-type: decimal;"><li>Die Forensoftware phpBB erstellt bei deinem Besuch des Boards mehrere Cookies. Cookies sind kleine Textdateien, die dein Browser als temporäre Dateien ablegt und die zwischen den einzelnen Aufrufen des Boards erhalten bleiben. In diesen Cookies sind die aktuelle ID deiner Sitzung (damit dir alle Seitenaufrufe zugeordnet werden können), Informationen über die von dir gelesenen Beiträge (zur Markierung dieser als gelesen/ungelesen; sofern du nicht angemeldet bist) sowie Informationen über deine Teilnahme an Umfragen (sofern du nicht angemeldet bist) gespeichert. Ferner werden deine Benutzer-ID, ein Authentifizierungsschlüssel und eine Session-ID gespeichert. Die Cookies haben standardmäßig eine Gültigkeit von einem Jahr. Alle Cookies kannst du jederzeit über die Funktion „Alle Cookies löschen“ löschen.</li>
```
Cookies werden doch auch gesetzt, wenn man nicht "angemeldet bleiben" auswählt. Auch für die kurzzeitige Anmeldung werden Cookies verwendet, allerdings geht die Session dann wieder verloren.

2018-11-18 17:08 UTC, gn36 commented on language/de_x_sie/ucp.php
> +		<ol style="list-style-type: decimal;"><li>Die Forensoftware phpBB erstellt bei Ihrem Besuch des Boards mehrere Cookies. Cookies sind kleine Textdateien, die Ihr Browser als temporäre Dateien ablegt
```suggestion
		<ol style="list-style-type: decimal;"><li>Die Forensoftware phpBB erstellt bei Ihrem Besuch des Boards mehrere Cookies. Cookies sind kleine Textdateien, die Ihr Browser als temporäre Dateien ablegt und die zwischen den einzelnen Aufrufen des Boards erhalten bleiben. In diesen Cookies sind die aktuelle ID Ihrer Sitzung (damit Ihnen alle Seitenaufrufe zugeordnet werden können), Informationen über die von Ihnen gelesenen Beiträge (zur Markierung dieser als gelesen/ungelesen; sofern Sie nicht angemeldet sind) sowie Informationen über Ihre Teilnahme an Umfragen (sofern Sie nicht angemeldet sind) gespeichert. Ferner werden Ihre Benutzer-ID, ein Authentifizierungsschlüssel und eine Session-ID gespeichert. Die Cookies haben standardmäßig eine Gültigkeit von einem Jahr. Alle Cookies können Sie jederzeit über die Funktion „Alle Cookies löschen“ löschen.</li>
```
Selbiges hier

2018-11-18 19:07 UTC, gn36 approved these changes

2018-11-18 21:24 UTC, Philipp-K requested changes
Sie dann analog

2018-11-18 21:24 UTC, Philipp-K commented on language/de/ucp.php
> +		<li>Wenn du einen Beitrag oder eine private Nachricht erstellst, so werden die dort eingegebenen Daten ebenfalls gespeichert. Gleiches gilt, wenn du einen Beitrag als Entwurf zwischenspeicherst. In
Korrekterweise passt hier "zwischengespeichert" nicht, da die Daten sonst nicht angezeigt werden könnten. "nicht dauerhaft gespeichert" wäre imho besser

2018-11-18 21:24 UTC, Philipp-K commented on language/de/ucp.php
> +		<p>Darüber hinaus ist der Betreiber berechtigt im Rahmen einer Interessenabwägung zwischen deinen und seinen Interessen sowie den Interessen Dritter, Zeitpunkte von Zugriffen und Aktionen zusammen
```suggestion
		<p>Darüber hinaus ist der Betreiber berechtigt, im Rahmen einer Interessenabwägung zwischen deinen und seinen Interessen sowie den Interessen Dritter, Zeitpunkte von Zugriffen und Aktionen zusammen mit deiner IP-Adresse und der von deinem Browser übermittelter Browser-Kennung zu speichern, sofern dies zur Gefahrenabwehr oder zur rechtlichen Nachverfolgbarkeit notwendig ist.</p>
```

Es geht ja um die Nachverfolgbarkeit von Änderungen etc.

2018-11-18 21:24 UTC, Philipp-K commented on language/de/ucp.php
> +		<p>Zweck eines Boards ist es, einen Austausch mit anderen Personen zu ermöglichen. Du bist dir daher bewusst, dass die Daten deines Profils und die von dir erstellten Beiträge im Internet öffentlic
```suggestion
		<p>Zweck eines Boards ist es, einen Austausch mit anderen Personen zu ermöglichen. Du bist dir daher bewusst, dass die Daten deines Profils und die von dir erstellten Beiträge im Internet öffentlich zugänglich sein können. Der Betreiber kann jedoch festlegen, dass einzelne Informationen nur für einen eingeschränkten Nutzerkreis (z. B. andere registrierte Benutzer, Administratoren etc.) zugänglich sind. Wenn du Fragen dazu hast, suche nach entsprechenden Informationen im Forum oder kontaktiere den Betreiber. Die E-Mail-Adresse aus deinem Profil ist dabei jedoch nur für den Betreiber und von ihm beauftragte Personen (Administratoren) zugänglich.</p>
```

2018-11-19 21:39 UTC, Philipp-K approved these changes

2018-11-19 22:20 UTC, merged