3.2.8/acp
phpbb-de/phpbb-translation pull request #390
Opened 2019-08-18 18:01 UTC by Philipp-K

2019-08-19 17:19 UTC, Crizz0 requested changes

2019-08-19 17:19 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Wie wärs mit: 

> Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht explizit ein Protokoll vorgegeben hat.

2019-08-19 17:19 UTC, Crizz0 commented on language/de/acp/forums.php
> +	'FORUM_NAME_EMOJI'					=> 'Der Name des Forums, den du eingegeben hast, ist ungültig.<br>Er enhtält die folgenden nicht unterstützten Zeichen:<br>%s',
Typo: 
> enhtält

2019-08-19 17:19 UTC, Crizz0 commented on language/de/acp/styles.php
> +	'ACP_STYLES_EXPLAIN'						=> 'Hier kannst du die auf deinem Board verfügbaren Styles verwalten.<br>Beachte bitte, dass du den Style „<strong>prosilver</strong>“ nicht deinstallieren kannst, da er de
"Standard- und primäre Eltern-Style" ? Oder "Vorfahren-Style"?

Liest sich mit dem - und dem übergeordnetnen Style schon ein wenig hölzern.

2019-08-19 17:19 UTC, Crizz0 commented on language/de_x_sie/acp/forums.php
> +	'FORUM_NAME_EMOJI'					=> 'Der Name des Forums, den Sie eingegeben haben, ist ungültig.<br>Er enhtält die folgenden nicht unterstützten Zeichen:<br>%s',
> enhtält

2019-08-19 19:51 UTC, Philipp-K commented on language/de/acp/styles.php
> +	'ACP_STYLES_EXPLAIN'						=> 'Hier kannst du die auf deinem Board verfügbaren Styles verwalten.<br>Beachte bitte, dass du den Style „<strong>prosilver</strong>“ nicht deinstallieren kannst, da er de
Wir haben halt bislang "übergeordneten Style" für "parent style" verwendet. Ich versuch's mal etwas freier

2019-08-19 19:52 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Das wäre aber inhaltlich eine andere Aussage.

2019-08-19 19:54 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Findest du? Ich wollte schon noch das Gleiche sagen. Nämlich, dass man das Protokoll nicht dazu schreibt, wenn es keine Info gibt, genau dies zu ergänzen.

2019-08-19 19:55 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Man könnte es umdrehen:

> Gebe nur dann ein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, wenn dir dein E-Mail-Provider mitgeteilt hat, eines anzugeben.

2019-08-19 20:03 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Wenn der Provider sagt: "Geben Sie explizit TSL als Protokoll an", ist die Sache eindeutig. Wenn der Provider aber sagt: "Der Server verwendet TSL" ist das nicht mehr der Fall.

2019-08-19 20:07 UTC, Crizz0 commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Ich finde den Anfang vom Satz gar nicht schlimm. Ich finde nur, es ließt sich nach hinten, nicht so gut:
> sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.

Vielleicht auch nur so:
> sofern dich dein E-Mail-Provider nicht informiert hat, eines anzugeben.

2019-08-19 20:36 UTC, Philipp-K commented on language/de/acp/board.php
> +	'SMTP_SERVER_EXPLAIN'			=> 'Gebe kein Protokoll (<samp>ssl://</samp> oder <samp>tsl://</samp>) an, sofern dir dein E-Mail-Provider nicht mitgeteilt hat, es anzugeben.',
Dann versuchen wir es doch so...

2019-08-22 20:36 UTC, Crizz0 approved these changes

2019-08-22 20:40 UTC, merged