Language changes from 3.2.8-RC1 to 3.2.8
phpbb-de/phpbb-translation pull request #392
Opened 2019-09-20 16:12 UTC by Crizz0

For #387 Number 2

2019-09-22 10:22 UTC, Philipp-K requested changes

2019-09-22 10:22 UTC, Philipp-K commented on language/de/common.php
> +	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'				=> 'Dieser externe Service wurde bereits mit einem anderen Benutzeraccount verknüpft.',
Ich würde "Benutzerkonto" schreiben, wie an anderen Stellen auch

2019-09-22 15:12 UTC, Crizz0 commented
Statt Benutzeraccount. 

Am 22. September 2019 12:22:27 MESZ schrieb Philipp-K <notifications@github.com>:
>Philipp-K requested changes on this pull request.>
>>
>>
>>
>> @@ -94,7 +94,7 @@>
>	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Die Bild-Datei, die du versucht hast
>hochzuladen, ist ungültig.',>
> 	'AUTHOR'						=> 'Autor',>
>	'AUTH_NO_PROFILE_CREATED'		=> 'Die Erstellung eines Mitgliederprofils
>ist gescheitert.',>
>-	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'				=> 'Das Konto wurde
>bereits mit einem anderen Benutzer verknüpft.',>
>+	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'				=> 'Dieser externe
>Service wurde bereits mit einem anderen Benutzeraccount verknüpft.',>
>>
>Ich würde "Benutzerkonto" schreiben, wie an anderen Stellen auch>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/phpbb-de/phpbb-translation/pull/392#pullrequestreview-291500021

2019-09-23 18:02 UTC, Philipp-K approved these changes

2019-09-23 18:19 UTC, merged