Änderungen für 3.2.9-RC1 to 3.2.9
phpbb-de/phpbb-translation pull request #402
Opened 2020-01-05 14:50 UTC by Crizz0

Fixes #399 Part 2

2020-01-05 15:45 UTC, gn36 approved these changes

2020-01-05 19:19 UTC, Philipp-K requested changes
Rich text characters ist imho schon im englischen unglücklich. Dann würde ich aber das zumindest als "Rich-Text-Zeichen" übertragen. Was steckt denn technisch genau dahinter?

2020-01-05 19:52 UTC, Crizz0 commented
Das ist eine neue Berechtigung, die es verbietet, dass man Emojis und Rich-Text eben im Thementitel verwenden kann. Das würde gewünscht von, nachdem es eingeführt wurde. 
Ergo sowas: 😆 oder sowas `"\f56d"`

2020-01-05 20:51 UTC, Philipp-K approved these changes

2020-01-06 18:29 UTC, gn36 approved these changes

2020-01-06 18:43 UTC, merged