Änderungen für 3.3.1-rc1 (Allgemeine Dateien)
phpbb-de/phpbb-translation pull request #409
Opened 2020-07-02 10:33 UTC by Philipp-K

2020-07-02 10:39 UTC, Crizz0 requested changes

2020-07-02 10:39 UTC, Crizz0 commented on language/de/captcha_recaptcha.php
> +	'RECAPTCHA_LANG'				=> 'en-GB',
Wir bleiben Deutsch, auch beim Captcha. Ergo auf 'de' ändern.

2020-07-16 12:58 UTC, Crizz0 requested changes

2020-07-16 12:58 UTC, Crizz0 commented on language/de/search.php
> +	'RETURN_FIRST_EXPLAIN'	=> 'Wenn 0 als Wert eingestellt wird, wird der komplette Beitrag angezeigt.',
Eine kürzere Version:
> Stelle 0 als Wert ein, damit der komplette Beitrag angezeigt wird. 

Diese "wird, wird" Dopplung finde ich nämlich nicht so schön.

2020-07-16 12:58 UTC, Crizz0 commented on language/de/migrator.php
> +	'MIGRATION_EXCEPTION_ERROR'			=> 'Während der Anpassung der Datenbank ist etwas falsch gelaufen und ein Fehler aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie
> so weit 

zu:
> soweit

2020-08-05 10:20 UTC, gn36 reviewed
Ist im Original identisch, aber http gibt es bei Google ja kaum noch...

2020-08-05 10:20 UTC, gn36 commented on language/de_x_sie/captcha_recaptcha.php
> +	'RECAPTCHA_NOT_AVAILABLE'		=> 'Um reCaptcha nutzen zu können, müssen Sie sich ein Konto auf <a href="http://www.google.com/recaptcha">www.google.com/recaptcha</a> anlegen.',
Auch https?

2020-08-10 19:45 UTC, Philipp-K commented on language/de/migrator.php
> +	'MIGRATION_EXCEPTION_ERROR'			=> 'Während der Anpassung der Datenbank ist etwas falsch gelaufen und ein Fehler aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie
Imho korrekt - https://www.sprachpingel.de/allgemein/so-weit

2020-08-11 17:20 UTC, Crizz0 commented on language/de/migrator.php
> +	'MIGRATION_EXCEPTION_ERROR'			=> 'Während der Anpassung der Datenbank ist etwas falsch gelaufen und ein Fehler aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie
okay, hast recht.

2020-08-11 17:22 UTC, Crizz0 approved these changes

2020-08-12 15:50 UTC, merged