Änderungen für 3.3.1-RC1 (ACP)
phpbb-de/phpbb-translation pull request #411
Opened 2020-07-02 10:48 UTC by Philipp-K

2020-07-02 11:29 UTC, Crizz0 commented on language/de/acp/board.php
> +	'PASSWORD_LENGTH_EXPLAIN'	=> 'Die Anzahl von Zeichen, aus denen ein Passwort mindestens bestehen muss. Es existiert keine Grenze für die maximale Länge des Passworts.',
`Die Anzahl von Zeichen... `das klingt irgendwie komisch, oder?

Bei anderen ähnlichen Sätzen haben wir oft "Anzahl an Zeichen"

2020-07-16 13:02 UTC, Crizz0 requested changes
Nur die Frage, wie wir PASSWORD_LENGTH_EXPLAIN formulieren oder es so lassen.

2020-08-05 10:03 UTC, gn36 commented on language/de/acp/board.php
> +	'PASSWORD_LENGTH_EXPLAIN'	=> 'Die Anzahl von Zeichen, aus denen ein Passwort mindestens bestehen muss. Es existiert keine Grenze für die maximale Länge des Passworts.',
Ich finde „an“ auch besser

2020-08-11 17:16 UTC, Crizz0 commented
@Philipp-K was meinst du zu dem einen Punkt?

2020-08-12 15:49 UTC, Crizz0 approved these changes

2020-08-12 15:49 UTC, merged