Anpassung der Kurzversionen
phpbb-de/phpbb-translation pull request #436
Opened 2021-04-06 18:00 UTC by Philipp-K

2021-04-07 17:46 UTC, Crizz0 requested changes

2021-04-07 17:46 UTC, Crizz0 commented on language/de/email/short/topic_notify.txt
> +Subject: Neues Thema in „{FORUM_NAME}“
Im Original heißt es:

> Subject: Reply in "{TOPIC_TITLE}"

2021-04-07 17:46 UTC, Crizz0 commented on language/de_x_sie/email/short/topic_notify.txt
> +Subject: Neues Thema in „{FORUM_NAME}“
Original lautet:

> Subject: Reply in "{TOPIC_TITLE}"

Wir müssen hier bei der gleichen Variable bleiben.

2021-04-07 17:46 UTC, Crizz0 commented on language/de/email/short/newtopic_notify.txt
> +im Forum „{FORUM_NAME}“ wurde ein neues Thema „{TOPIC_TITLE}“<!-- IF AUTHOR_NAME != '' --> von {AUTHOR_NAME}<!-- ENDIF --> erstellt, seitdem du „{SITENAME}“ zuletzt besucht hast. Du erhältst keine we
In en/ nutzen sie Plural, wäre hier (und in anderen Dateien) dann 

> Du erhältst keine weiteren Benachrichtigungen, bis du das Forum besucht hast.

was sich imo ein bisschen besser anhört.

2021-04-07 17:46 UTC, Crizz0 commented on language/de/email/privmsg_notify.txt
> +Subject: Neue Private Nachricht
Das ist nicht die "short"-Version. Diese hier hast du schon mal in https://github.com/phpbb-de/phpbb-translation/pull/432/files angepasst.

2021-04-07 17:46 UTC, Crizz0 commented on language/en/email/short/newtopic_notify.txt
>  If you no longer wish to watch this forum you can either click the "Unsubscribe forum" link found in the forum above, or by clicking the following link:
`If you no longer wish to watch this forum click the following link:`

2021-05-02 14:27 UTC, Philipp-K commented on language/de_x_sie/email/short/topic_notify.txt
> +Subject: Neues Thema in „{FORUM_NAME}“
Da ist was ganz quer gelaufen...

2021-05-02 14:31 UTC, Philipp-K commented on language/de/email/short/newtopic_notify.txt
> +im Forum „{FORUM_NAME}“ wurde ein neues Thema „{TOPIC_TITLE}“<!-- IF AUTHOR_NAME != '' --> von {AUTHOR_NAME}<!-- ENDIF --> erstellt, seitdem du „{SITENAME}“ zuletzt besucht hast. Du erhältst keine we
Meiner Ansicht nach ist es aber im Singular besser. Da ist nämlich klar, dass es sich nur auf diese Art der Benachrichtigung bezieht - und nicht auf jegliche Benachrichtigungen des Forums

2021-05-02 15:35 UTC, Crizz0 commented on language/de/email/short/newtopic_notify.txt
> +im Forum „{FORUM_NAME}“ wurde ein neues Thema „{TOPIC_TITLE}“<!-- IF AUTHOR_NAME != '' --> von {AUTHOR_NAME}<!-- ENDIF --> erstellt, seitdem du „{SITENAME}“ zuletzt besucht hast. Du erhältst keine we
okay, dann lassen wir es so. 👍

2021-05-02 15:42 UTC, Crizz0 approved these changes

2021-05-02 15:44 UTC, merged