Scanialady 336rc1 patch 1
phpbb-de/phpbb-translation pull request #443
Opened 2022-01-23 13:51 UTC by Scanialady

Änderungen für phpBB 3.3.6-RC1 de/de-x-sie attachment.php/migrator.php

2022-01-23 13:52 UTC, Crizz0 commented
Die Änderungen für "english" müssen auch ergänzt werden.

2022-01-23 21:08 UTC, Philipp-K requested changes

2022-01-23 21:08 UTC, Philipp-K commented on language/de/acp/attachments.php
> +	'UPLOAD_POST_NOT_EXIST'			=> 'Datei “%1$s” kann nicht zu Beitrag Nummer %2$d hochgeladen werden, weil der Beitrag nicht existiert.',
Bitte korrekte Anführungszeichen verwenden: „xxx“

2022-01-23 21:08 UTC, Philipp-K commented on language/de/acp/attachments.php
> +	'UPLOAD_POST_NOT_EXIST'			=> 'Datei “%1$s” kann nicht zu Beitrag Nummer %2$d hochgeladen werden, weil der Beitrag nicht existiert.',
Ich würde "für Beitrag" statt "zu Beitrag" schreiben. Evtl. auch kürzen: Datei „%1$s“ kann nicht hochgeladen werden, da der Beitrag Nummer %2$d nicht existiert.

2022-01-23 21:08 UTC, Philipp-K commented on language/de/migrator.php
> +	'ROLE_ASSIGNED_NOT_EXIST'			=> 'Die der Gruppe "%1$s" zugewiesene Berechtigungsrolle existiert unerwarteterweise nicht. Rollen-ID: "%2$s"',
Berechtigungs-Rolle (wie eine Zeile weiter unten)

2022-01-23 21:08 UTC, Philipp-K commented on language/de/migrator.php
> +	'ROLE_ASSIGNED_NOT_EXIST'			=> 'Die der Gruppe "%1$s" zugewiesene Berechtigungsrolle existiert unerwarteterweise nicht. Rollen-ID: "%2$s"',
unerwarteterweise -> überraschend (ist zwar nicht 100 prozentig korrekt, aber weniger sperrig und entspricht eher dem deutschen Sprachusus)
Rollen-ID -> ID der Rolle

2022-01-24 15:20 UTC, Scanialady commented on language/de/migrator.php
> +	'ROLE_ASSIGNED_NOT_EXIST'			=> 'Die der Gruppe "%1$s" zugewiesene Berechtigungsrolle existiert unerwarteterweise nicht. Rollen-ID: "%2$s"',
Ok, habe es geändert.

2022-02-09 19:28 UTC, Philipp-K approved these changes

2022-03-06 17:49 UTC, merged