Change for phpBB 3.3.6-RC1 to 3.3.6
phpbb-de/phpbb-translation pull request #445
Opened 2022-03-15 21:12 UTC by Crizz0

Fixes #442

2022-03-18 19:36 UTC, DrDeath approved these changes

2022-03-18 20:10 UTC, gn36 approved these changes
Englische Änderung der FAQ gibt es nicht? Die Änderungen ansich sind ok.

2022-03-18 20:21 UTC, gn36 requested changes

2022-03-18 20:21 UTC, gn36 commented on language/de/install.php
> +		<p>Das „Erweiterte-Update-Paket“ wird nur in dem Fall empfohlen, wenn in deiner Installation die phpBB-Hauptdateien verändert wurden. Du kannst deine Installation auch mit den in der INSTALL.html b
Sorry, Korrektur: da fehlt eine Ersetzung:
```suggestion
		<p>Das „Erweiterte-Update-Paket“ wird nur in dem Fall empfohlen, wenn in deiner Installation die phpBB-Hauptdateien verändert wurden. Du kannst deine Installation auch mit den in der INSTALL.html beschriebenen Methoden aktualisieren. Zum erweiterten Update von phpBB musst du folgende Schritte ausführen:</p>
```

2022-03-18 20:21 UTC, gn36 commented on language/de_x_sie/install.php
> +		<p>Das „Erweiterte-Update-Paket“ wird nur in dem Fall empfohlen, wenn in Ihrer Installation die phpBB-Hauptdateien verändert wurden. Sie können Ihre Installation auch mit den in der INSTALL.html be
```suggestion
		<p>Das „Erweiterte-Update-Paket“ wird nur in dem Fall empfohlen, wenn in Ihrer Installation die phpBB-Hauptdateien verändert wurden. Sie können Ihre Installation auch mit den in der INSTALL.html beschriebenen Methoden aktualisieren. Zum erweiterten Update von phpBB müssen Sie folgende Schritte ausführen:</p>
```

2022-03-19 07:54 UTC, DrDeath requested changes

2022-03-19 07:54 UTC, DrDeath commented on language/de/install.php
> +		<h1>Wie du ein Update deiner Installation mit dem „Erweiterte-Update-Paket“ durchführst</h1>
```suggestion
		<h1>Wie du ein Update deiner Installation mit dem „Erweiterten-Update-Paket“ durchführst</h1>
```

2022-03-19 07:54 UTC, DrDeath commented on language/de_x_sie/install.php
> +		<h1>Wie Sie ein Update Ihrer Installation mit dem „Erweiterte-Update-Paket“ durchführen</h1>
```suggestion
		<h1>Wie Sie ein Update Ihrer Installation mit dem „Erweiterten-Update-Paket“ durchführen</h1>
```

2022-03-19 13:28 UTC, merged