Änderungen für phpBB 3.3.10-RC1 an common.php
phpbb-de/phpbb-translation pull request #457
Opened 2023-01-16 20:43 UTC by Crizz0

Für #456. 

Änderungen an CDN Beschriftung sind in #455

2023-02-08 07:28 UTC, gn36 requested changes

2023-02-08 07:28 UTC, gn36 commented on language/de/common.php
> +	'ROUTE_INVALID_MISSING_PARAMS'	=> 'An die Route „%s“ wurden ungültige oder fehlende Parameter übergeben.',
Fehlende Parameter kann man nicht wirklich übergeben... Vielleicht besser:
```suggestion
	'ROUTE_INVALID_MISSING_PARAMS'	=> 'Parameter für die Route „%s“ sind ungültig oder fehlen.',
```

2023-02-08 17:59 UTC, gn36 approved these changes
"Die übergebenen Parameter" statt einfach nur "Parameter" würde auch noch gehen, finde ich auch besser als meinen ursprünglichen Vorschlag, aber so ist auch ok.

2023-02-08 20:41 UTC, Philipp-K commented
Was ist denn hier der Kontext, in dem das verwendet wird? Wenn ich das richtig sehe, wird das im Kontext von HTTP-Weiterleitungen (routing) verwendet. Dann würde ich eher von "Weiterleitung" sprechen.

2023-02-08 20:45 UTC, Crizz0 commented
> Was ist denn hier der Kontext, in dem das verwendet wird? Wenn ich das richtig sehe, wird das im Kontext von HTTP-Weiterleitungen (routing) verwendet. Dann würde ich eher von "Weiterleitung" sprechen.

https://github.com/phpbb/phpbb/blob/3914f1ec41d3b9da2aa910209f1fc3b453586bb0/phpBB/cron.php

2023-02-09 20:07 UTC, Philipp-K commented
Auf den Link habe ich keinen Zugriff :-(

2023-02-09 20:08 UTC, Crizz0 commented
> Auf den Link habe ich keinen Zugriff :-(

Geht nur, wenn du dich mit deinem phpBB.com Account dort angemeldet hast. Als Gast geht es nicht.

2023-02-09 21:13 UTC, Philipp-K approved these changes

2023-02-09 21:14 UTC, merged