Änderungen für Final 3.3.10
phpbb-de/phpbb-translation pull request #458
Opened 2023-02-06 18:51 UTC by Crizz0

For: #456

2023-02-07 18:45 UTC, Crizz0 commented
Bei den en/ hab ich die von 3.3.10 drauf kopiert, deshalb sind da auch noch ein paar zusätzliche Kleinigkeiten korrigiert worden.

2023-02-08 07:35 UTC, gn36 approved these changes

2023-02-08 07:35 UTC, gn36 commented
Evtl. Anfragenlimit -> Anfragen-Limit? Aber muss in meinen Augen nicht sein.

2023-02-08 11:08 UTC, Crizz0 commented
> Evtl. Anfragenlimit -> Anfragen-Limit? Aber muss in meinen Augen nicht sein.

Hatte es jetzt analog zu Kreditlimit, Datenlimit, Tempolimit etc. zusammengeschrieben.

2023-02-08 17:56 UTC, gn36 commented
Ist ok. Es gibt ja doch ein paar Dinge die wir mit Bindestrich geschrieben haben. Tendenziell hätte ich es auch zusammengeschrieben.

2023-02-08 20:44 UTC, Philipp-K requested changes

2023-02-08 20:44 UTC, Philipp-K commented on language/de/acp/common.php
> +	'LOG_SPAMHAUS_OPEN_RESOLVER'	=> 'Spamhaus erlaubt keine Anfragen mit einem offenen Resolver. Die Blacklist-Prüfung wurde deaktiviert. Unter: https://www.spamhaus.com/product/help-for-spamhaus-public
Ich würde hier von "DNS-Resolver" sprechen

2023-02-08 21:15 UTC, Crizz0 commented on language/de/acp/common.php
> +	'LOG_SPAMHAUS_OPEN_RESOLVER'	=> 'Spamhaus erlaubt keine Anfragen mit einem offenen Resolver. Die Blacklist-Prüfung wurde deaktiviert. Unter: https://www.spamhaus.com/product/help-for-spamhaus-public
Macht es verständlicher. Bau ich ein.

2023-02-09 20:03 UTC, Philipp-K commented on language/de/acp/common.php
> +	'LOG_SPAMHAUS_OPEN_RESOLVER'	=> 'Spamhaus erlaubt keine Anfragen mit einem offenen DNS-Resolver. Die Blacklist-Prüfung wurde deaktiviert. Unter: https://www.spamhaus.com/product/help-for-spamhaus-pu
Sorry, gerade erst gesehen: die Doppelpunkte vor der URL gehören meiner Ansicht nach raus

2023-02-09 20:42 UTC, Philipp-K approved these changes

2023-02-09 21:15 UTC, merged