Änderungen für phpBB 3.3.11
phpbb-de/phpbb-translation pull request #461
Opened 2023-10-21 09:57 UTC by Crizz0

- [x] en/
- [ ] de/
- [ ] de_x_sie
- [ ] Readme.md

2023-10-21 17:22 UTC, Scanialady commented on language/de/acp/permissions.php
> +	'ACL_SET_EXPLAIN'		=> 'Berechtigungen basieren auf einem einfachen <strong>JA/NEIN</strong>-System. Wird eine Einstellung für einen Benutzer oder eine Gruppe auf <strong>NIE</strong> gesetzt, so übe
```suggestion
	'ACL_SET_EXPLAIN'		=> 'Berechtigungen basieren auf einem einfachen <strong>JA/NEIN</strong>-System. Wird eine Einstellung für einen Benutzer oder eine Gruppe auf <strong>NIE</strong> gesetzt, so überschreibt dieser Wert alle anderen gesetzten Werte. Wenn du bei diesem Benutzer/dieser Gruppe keinen Wert für eine Einstellung vornehmen möchtest, wähle <strong>NEIN</strong> aus. Wenn an anderer Stelle eine abweichende Einstellung vorgenommen wurde, so wird diese verwendet; ansonsten wird von <strong>NIE</strong> ausgegangen. Alle (mit dem davorstehendem Kontrollkästchen) ausgewählten Objekte werden die von dir definierten Berechtigungen übernehmen. Bitte beachte, dass es keinen Effekt hat Administrator-Berechtigungen für Gründer-Benutzeraccounts zu definieren, da Administrations-Berechtigungen für Gründer-Benutzeraccounts immer auf <strong>JA</strong> eingestellt sind.',
```

2023-10-21 17:23 UTC, Scanialady commented on language/de/acp/search.php
> +		2	=> 'Die Beiträge bis zur Beitrag-ID #%2$d wurden bereits indiziert, davon %1$d Beiträge in diesem Durchgang.',
```suggestion
		2	=> 'Die Beiträge bis zur Beitrags-ID #%2$d wurden bereits indiziert, davon %1$d Beiträge in diesem Durchgang.',
```

2023-10-21 17:30 UTC, Scanialady commented on language/de/install.php
> +	'INTRODUCTION_BODY'		=> 'Willkommen bei phpBB3!<br /><br />phpBB ist die am weitesten verbreitete Open-Source-Forensoftware. phpBB3 ist die jüngste Fortsetzung einer im Jahr 2000 begonnenen Entwickl
```suggestion
	'INTRODUCTION_BODY'		=> 'Willkommen bei phpBB3!<br /><br />phpBB ist die am weitesten verbreitete Open-Source-Forensoftware. phpBB3 ist die jüngste Fortsetzung einer im Jahr 2000 begonnenen Entwicklungsgeschichte. Wie seine Vorversionen ist phpBB3 funktionsreich, benutzerfreundlich und vollständig vom phpBB-Team unterstützt. phpBB3 verbessert deutlich, was phpBB2 beliebt gemacht hat und bringt neue Funktionen, die häufig gefragt und nicht in den Vorversionen enthalten waren. Wir hoffen, dass es deine Erwartungen übertrifft.<br /><br />Dieses Installations-System wird dich durch die Installation von phpBB3, das Update von einer älteren auf die aktuelle Version von phpBB3, und auch durch die Konvertierung von einem anderen Software-Paket (inklusive phpBB2) führen. Für weitere Informationen empfehlen wir dir, <a href="%1$s">die Installationsanweisungen</a> zu lesen.<br /><br />Um die Lizenz von phpBB3 zu lesen oder Informationen über den Erhalt von Support und unsere Einstellung dazu zu erhalten, wähle bitte die entsprechende Option aus dem seitlichen Menü aus. Um fortzufahren, wähle bitte oben das entsprechende Register aus.',
```

2023-10-21 17:55 UTC, Scanialady requested changes
"Wenn an anderer Stelle eine (abweichende) Einstellung vorgenommen wurde, so wird diese verwendet; ansonsten wird von <strong>NIE</strong> ausgegangen." 
- nee, eigentlich nicht. Wenn IRGENDWO "nie" steht, dann überschreibt das immer. Falls ich den Text korrekt verstehe.

2023-10-21 17:55 UTC, Scanialady commented on language/de_x_sie/acp/permissions.php
> +	'ACL_SET_EXPLAIN'		=> 'Berechtigungen basieren auf einem einfachen <strong>JA/NEIN</strong>-System. Wird eine Einstellung für einen Benutzer oder eine Gruppe auf <strong>NIE</strong> gesetzt, so übe
```suggestion
	'ACL_SET_EXPLAIN'		=> 'Berechtigungen basieren auf einem einfachen <strong>JA/NEIN</strong>-System. Wird eine Einstellung für einen Benutzer oder eine Gruppe auf <strong>NIE</strong> gesetzt, so überschreibt dieser Wert alle anderen gesetzten Werte. Wenn Sie bei diesem Benutzer/dieser Gruppe keinen Wert für eine Einstellung vornehmen möchten, wählen Sie <strong>NEIN</strong> aus. Wenn an anderer Stelle eine abweichende Einstellung vorgenommen wurde, so wird diese verwendet; ansonsten wird von <strong>NIE</strong> ausgegangen. Alle (mit dem davorstehendem Kontrollkästchen) ausgewählten Objekte werden die von Ihnen definierten Berechtigungen übernehmen.  Bitte beachten Sie, dass es keinen Effekt hat Administrator-Berechtigungen für Gründer-Benutzeraccounts zu definieren, da Administrations-Berechtigungen für Gründer-Benutzeraccounts immer auf <strong>JA</strong> eingestellt sind.',
```

2023-10-21 17:55 UTC, Scanialady commented on language/de_x_sie/acp/search.php
> +		2	=> 'Die Beiträge bis zur Beitrag-ID #%2$d wurden bereits indiziert, davon %1$d Beiträge in diesem Durchgang.',
```suggestion
		2	=> 'Die Beiträge bis zur Beitrags-ID #%2$d wurden bereits indiziert, davon %1$d Beiträge in diesem Durchgang.',
```

2023-10-21 17:55 UTC, Scanialady commented on language/de_x_sie/install.php
> +	'INTRODUCTION_BODY'		=> 'Willkommen bei phpBB3!<br /><br />phpBB ist die am weitesten verbreitete Open-Source-Forensoftware. phpBB3 ist die jüngste Fortsetzung einer im Jahr 2000 begonnenen Entwickl
```suggestion
	'INTRODUCTION_BODY'		=> 'Willkommen bei phpBB3!<br /><br />phpBB ist die am weitesten verbreitete Open-Source-Forensoftware. phpBB3 ist die jüngste Fortsetzung einer im Jahr 2000 begonnenen Entwicklungsgeschichte. Wie seine Vorversionen ist phpBB3 funktionsreich, benutzerfreundlich und vollständig vom phpBB-Team unterstützt. phpBB3 verbessert deutlich, was phpBB2 beliebt gemacht hat und bringt neue Funktionen, die häufig gefragt und nicht in den Vorversionen enthalten waren. Wir hoffen, dass es Ihre Erwartungen übertrifft.<br /><br />Dieses Installations-System wird Sie durch die Installation von phpBB3, das Update von einer älteren auf die aktuelle Version von phpBB3, und auch durch die Konvertierung von einem anderen Software-Paket (inklusive phpBB2) führen. Für weitere Informationen empfehlen wir Ihnen, <a href="%1$s">die Installationsanweisungen</a> zu lesen.<br /><br />Um die Lizenz von phpBB3 zu lesen oder Informationen über den Erhalt von Support und unsere Einstellung dazu zu erhalten, wählen Sie bitte die entsprechende Option aus dem seitlichen Menü aus. Um fortzufahren, wählen Sie bitte oben das entsprechende Register aus.',
```

2023-10-24 18:45 UTC, Philipp-K requested changes

2023-10-24 18:45 UTC, Philipp-K commented on language/de/acp/board.php
> +	'DEFAULT_DATE_FORMAT_EXPLAIN'	=> 'Die Syntax entspricht dem gleichen Format der <a href="https://www.php.net/manual/datetime.format.php">date-Funktion</a> von PHP.',
Imho besser: Es wird die gleiche Syntax wie bei den Datums-Funktionen von PHP verwendet. Der Verweis auf die date-Funktion ist hier auf jeden Fall falsch

2023-10-24 18:45 UTC, Philipp-K commented on language/de/acp/permissions.php
> +	'ACL_SET_EXPLAIN'		=> 'Berechtigungen basieren auf einem einfachen <strong>JA/NEIN</strong>-System. Wird eine Einstellung für einen Benutzer oder eine Gruppe auf <strong>NIE</strong> gesetzt, so übe
Etwas freier: Bitte beachte, dass die Festlegung von Administrator-Rechten für Gründer keine Auswirkungen haben wird, da die Administrations-Berechtigungen für Gründer-Benutzeraccounts immer auf <strong>JA</strong> eingestellt sind.

2023-10-24 18:45 UTC, Philipp-K commented on language/de/install.php
> +	'COLLIDING_USERNAMES_FOUND'			=> 'Es wurden doppelte Benutzernamen in deinem Board gefunden. Um mit der Konvertierung fortzufahren, müssen diese Benutzer gelöscht oder umbenannt werden, so dass in d
Etwas freier: so dass in deinem alten Board jeder bereinigte Benutzername nur für einen Benutzer (alternativ: einmal) verwendet wird.

2023-10-24 18:45 UTC, Philipp-K commented on language/de_x_sie/install.php
> +	'CONV_ERR_FATAL'					=> 'Konvertierung: Fatal-Error',
Schwerer Fehler bei der Konvertierung

2023-10-24 18:49 UTC, Crizz0 commented on language/de/acp/board.php
> +	'DEFAULT_DATE_FORMAT_EXPLAIN'	=> 'Die Syntax entspricht dem gleichen Format der <a href="https://www.php.net/manual/datetime.format.php">date-Funktion</a> von PHP.',
und den Link dann um Datums-Funktionen setzen?

2023-10-25 18:41 UTC, Scanialady approved these changes

2023-10-30 17:10 UTC, merged